### ISSUE TITLE
WCAG-checkup

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1018]
**Tasks**

* [ ] Add alt-text to header logo
* [ ] Set disabled link (in the steps for example) color from #9ea4a9 to #767676 (see [reason](https://jxnblk.com/grays/) )
* [ ] Set "Sign above" text to from color #c3c3c3 to #767676
* [ ] Set default line-height to 1.5
* [ ] h1 to h4 are not styled (explicitly) and can be used in the content field. Please add some default styling.

**Comment by sergei-maertens** [comment]
https://www.w3docs.com/tools/color-analyzer is useful to check color contrast

**Comment by joeribekker** [comment]
@sergei-maertens antwoord op je vraag bij taak 1: "Terug naar de hoofdsite" oid

**Comment by sergei-maertens** [comment]
ah, that was a question by Bart :-) the exact Dutch text will be handled in translations, but it's something like that.
