### ISSUE TITLE
Links toevoegen aan TinyMCE editors

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1080]
Is this easilly added?

![image](https://user-images.githubusercontent.com/96970/146039728-c5178e11-f39f-4a5e-a2d6-08931c4f0e14.png)

**Tasks**

* [x] Add links to ALL TinymCE editors
* [x] Add validator for these editors that links are allowed by the netloc list (global config)
* [x] Match Django and React widget options
* [x] Share widget options via JSON file.
* [x] Set the React widget to NL/current language like Django does (Tip van Sergei volgt via Slack)
* [x] ~Update language in Django settings by updating loaded JSON~ django-tinymce does this automatically

**Comment by Bartvaderkin** [comment]
One complication would be that the URLs in the emails are filtered against the CORS domain list, so links to random domains would disappear unless we make it dynamic somehow.

**Comment by joeribekker** [comment]
Urgh, really? But why?

**Comment by sergei-maertens** [comment]
I believe Bart is mixing things up - links are not verified against the CORS settings, but the allow-list of domains which is a separate config option (and stored in the database, where-as CORS is a deploy-time setting).
