### ISSUE TITLE
Payment is not set when a StUF-Zaak is created

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1085]
The StUF-ZDS plugin basically does:

```
        client.create_zaak(zaak_id, zaak_data, extra_data)
```

but the signature is:

```
def create_zaak(
        self, zaak_identificatie, zaak_data, extra_data, payment_required=False
    ):
```

This causes `betalingsIndicatie` to be set to `"N.v.t"` while it should `(Nog) niet`.

The payment also didn't seem to register but maybe that happened after other triggers (maybe the name is weird, since the payment did "register")?
![image](https://user-images.githubusercontent.com/96970/146387468-01b29afc-016e-4dc4-b24b-d3c8b5caf991.png)

Even if that worked, the `update_submission_payment_status` celery task seems to fail (which could have "overwritten" the `betalingsIndicatie="N.v.t"` to `Geheel` to fix the previous issue):

`update_submission_payment_status` calls `update_submission_payment_registration` and gives:

```
2021-12-16 15:08:33,881 INFO openforms.payments.tasks  Updating payment information for submission 440 (if needed!)
2021-12-16 15:08:33,928 INFO openforms.payments.tasks  Updating submission payment registration failed
Traceback (most recent call last):
  File "/app/src/openforms/payments/tasks.py", line 28, in update_submission_payment_status
    update_submission_payment_registration(submission)
  File "/app/src/openforms/payments/services.py", line 47, in update_submission_payment_registration
    plugin.update_payment_status(submission, options_serializer.validated_data)
  File "/app/src/openforms/registrations/contrib/stuf_zds/plugin.py", line 195, in update_payment_status
    client.set_zaak_payment(submission.registration_result["zaak"])
  File "/app/src/stuf/stuf_zds/client.py", line 283, in set_zaak_payment
    return self.partial_update_zaak(zaak_identificatie, data)
  File "/app/src/stuf/stuf_zds/client.py", line 261, in partial_update_zaak
    context = self._get_request_base_context()
  File "/app/src/stuf/stuf_zds/client.py", line 116, in _get_request_base_context
    "gemeentecode": self.options["gemeentecode"],
KeyError: 'gemeentecode'
```

![image](https://user-images.githubusercontent.com/96970/146386607-3f04c1ab-d94d-43b7-97cf-95a74c44379a.png)

**Tasks**

* [x] Pass the payment paramter to the create_zaak
* [x] Fix the gemeentecode issue so the task can be run
* [x] Write test to proof this issue is fixed
