### ISSUE TITLE
DigiD session timeout needs to be 15 minutes

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1138]
![image](https://user-images.githubusercontent.com/96970/147759191-e4661f5b-771f-42dd-8253-48f8c00c5e9b.png)

**Tasks**

* [x] Validate max value <= 15 for form session timeout (in global config)
* [x] If user sets more than 15, show warning that it cannot be more due to DigiD requirements.
* [x] Add data migration that sets this value to 15
