### ISSUE TITLE
Test results latest build

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1174]
Tested against version 5a8a30a35254ffedd1c9934654d911782eb53b93.

* Test form: `demo-sprint-11-testing` on the Maykin test env
* Admin interface in regular browser window
* Filling out the form in incognito window, Brave (Chromium 96) 

---

**Form designer**

- [x] BUG: Configuring appointments: added a phone number field in a different step, re-used a generic appointment fields step -> cannot configure the phone number component (dropdown does not change state) @sergei-maertens (fixed in 1ed8b77e24a73dca40b0a5ef2fa383327f025c88)
- [ ] #1190
- [ ] #1191
    - manual formatting (newlines, indentation) is reset when valid JSON is detected which outputs it all on a single line
    - font not being code/monospace makes it hard to read/edit the JSON
    - cursor jumps around once valid JSON is entered
    - basically currently the best way is to define the JSON in a code editor and then copy paste it into the form field
- [x] BUG: the complex JSON logic uses validation for simple logic at the moment, effectively making `and` and combined logic rules impossible to use. Caused by refactor with pricing/form logic & added validators. (fixed in a78d6b9fb0148a283ade0ab2e69a7b15038e21c0)

**Filling out the form**

- [x] BUG: Logging in with DigiD (login optional) brings the SDK into an infinite loading loop. Unsure what causes it, might be pre-fill related? @sergei-maertens (fixed in open-formulieren/open-forms-sdk#142)
    - It works when starting the form as anonymous user (!)
- [x] BUG: Multiple inputs (textfield) are broken (again) because of immutable state. The `+ add another` button click triggers this (likely fixed by https://github.com/open-formulieren/open-forms-sdk/pull/136) fix: open-formulieren/open-forms-sdk#142
- [x] BUG: Fieldset show/hide based on checkbox with default value `true` behaved a bit weird, but may be because of invalid logic configuration. To double check.
- [x] BUG: the WYSIWYG editor for the confirmation page template correctly allows arbitrary hyperlinks (filtering should only be done for templates going to e-mails w/r to phishing protection), however when the SDK renders this the URL appears to have been filtered out. Possibly some sanitation happens that shouldn't, OR the validator should be slapped on that field instead so users know to add it to the netloc allow list. @Bartvaderkin (fixed by https://github.com/open-formulieren/open-forms/pull/1177/commits/190c09c065852ddd02a2862d0768dba302dba118)
- [x] ??: background processing to quite a long time - might be because test server is overloaded, might be because of cold caches -> check again soon-ish
- [x] IMPROVEMENT: submissions admin show form step dropdown for every submission step inline. This will get worse the more form-steps there are -> should be `raw_id_field` widget @Bartvaderkin  or @joeribekker 
- [x] There's a `console.log` that was left in `FormStep.js` that shouldn't be
- [x] BUG: changing an appointment is very broken
    - The product data is not (pre)selected in the dropdown
    - The location data is not (pre)selected in the dropdown
    - The selected date is not pre-selected and because of that displayed in a "system" format (ISO-8601 instead of human readable)
    - The selected time is not pre-selected and because of that displayed in a "system" format (ISO-8601 instead of human readable)
    - It does not appear that the options are properly loaded from the backend.
- [x] ~~BUG: changing an appointment that was already paid still makes you pay again~~ could not reproduce on re-test
- [x] BUG: number field with comma's in overview page is displayed with dot (`.`) instead comma (`,`) decimal separator. Also same problem in the PDF confirmation @Bartvaderkin  (fixed in #1185 and open-formulieren/open-forms-sdk#145)
- [x] BUG: confirmation PDF order does not meet order of form steps (regression of #750) @Bartvaderkin (fixed in #1186)
- [x] BUG (?): appointment change does not require re-authentication, but might be because anonymous option is available too
