### ISSUE TITLE
File uploads and file size issues

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1193]
**Tasks**

* [x] Set and document Nginx default upload limit for the specific upload endpoint (suggestion: 50 MB)
* [x] Check and/or fix Open Forms configured upload limit (if configured to 1 MB, check that you cannot upload a file of 2 MB)
* [x] Show Nginx configured upload limit in Open Forms for upload fields (maybe even validate that it doesn't exceed this value)
* [x] For registration e-mails, do **not** add files as attachment but instead provide URLs to download these from the Open Forms server.
* [x] E-mail attachments can only be downloaded if you provide a valid hash or whatever as query-param.
* [x] For the confirmation email, only the file name is shown and the files are **not** attached
* [x] Make sure attachments (the actual files!) are also deleted when submissions are deleted.
* [x] Properly style file upload errors:
   ![image](https://user-images.githubusercontent.com/5518550/152831153-f958f1fd-89cb-4401-b171-737a43a4565e.png)
