### ISSUE TITLE
Create health check endpoint/push feature

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1204]
Open Forms knows best if Open Forms is working correctly.

We want to check the following things (feel free to add other stuff):

**Checks**

* [ ] Used SSL certificates used under the hood have 7+ days left before they expire
* [ ] Enabled plugins are functional (re-use Configuration overview stuff)
* [ ] All (related) Docker containers are operational
* [ ] Connection to Redis works
* [ ] Connection to database works
* [ ] The email queue does not have more than 1 pending message

**Tasks**

* [ ] Add feature to check all above checks, result should be a dict with all checks performed and their status (success/fail)
* [ ] Send a HTTP 200 if all OK, to configured endpoint. If something is not OK, don't sent anything.
