### ISSUE TITLE
Export includes upload domain, this should not be in there and dynamically set

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1208]
Exporting a form contains the upload URL. This is required by FormIO but this makes sharing forms a little bit leaky AND changing the domain name basically invalidates the FormIO configuration.

**Tasks**

* [ ] Remove FormIO upload URL from definitions (or replace with: `https://www.example.com`) upon export
* [ ] Dynamically use the configured domain instead of storing the domain hardcoded in JSON.
* [ ] Upon import, set the correct domain (not needed when the above works?)
