### ISSUE TITLE
Analytics tools should manage CSP and Cookie settings automatically

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1294]
This builds a little bit on #1616 which already added CSP settings AND includes a small piece to update them for siteimprove specific: https://github.com/open-formulieren/open-forms/pull/1650/files#diff-62f4fbe89de37783a7145fa240746d1930688dc41b30cf1523a70416bdae7ba5R486

**Tasks**

* [x] Move analytic HTML/JS snippets and config-model fields to a separate app
* [x] Create contrib folder that has subfolder for each analytics-tool
* [x] Add a JSON file for cookies for each analytic-tool
* [x] Add explicit enabled boolean field to enable/disable specific anytlic tool
* [x] When enabled, load JSON file for that analytic tool and modify domain
* [x] When enabled, set proper CSP headers (see siteimprove for example)
* [x] When disabled, remove the created entries for cookies and csp
* [x] When enabled/disabled, create timeline log entries that this caused the creation/deletion of cookies/csp entries
* [x] Add specific documentation
