### ISSUE TITLE
Test the new formio formatters

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1301]
As part of #1068, Steven implemented Formio formatters in a pluggable way (which is to be used in the PDFs and confirmation e-mail). This is configured behind a [feature flag](https://github.com/open-formulieren/open-forms/blob/master/src/openforms/config/models.py#L350)

So far this functionality has not been properly tested, which this ticket is about:

* manual testing
* automated testing

The current tests contain json fixtures for Formio: https://github.com/open-formulieren/open-forms/tree/master/src/openforms/formio/formatters/tests/files. These are a bit duplicated from https://github.com/open-formulieren/open-forms/tree/master/src/openforms/registrations/contrib/camunda/tests/files. These fixtures have been created by following these steps:

1. In the form designer admin, create a form with a single form step
2. Add all possible components to the form step
    * Make sure to have a single value variant
    * Make sure to have a multiple values variant (if applicable for the component type)
    * (new) Include variants of components for every option that may alter the representation (for example number of decimals for number/currency fields)
3. Save the data & form
4. Get the JSON configuration from the form definition detail/configuration endpoint and save to JSON file for tests (`all_components.json`)
5. Fill out the from from the UI and complete it
6. Save the `SubmissionStep.data` JSON to `all_components_data.json`

Once the fixtures have been generated/updated, define/update formatter tests (see https://github.com/open-formulieren/open-forms/blob/master/src/openforms/formio/formatters/tests/test_default_formatters.py#L21) for the legacy behaviour which is supposed to be mostly correct. The Camunda contrib should use the same `formio` fixtures, so remove the duplicated files/fixtures there.

Once that is in place (and any possible bugs fixed, for example the signature representation is not right yet - see #1293 and #1179), update the test to enable the feature flag and ensure it passes too. Fix any formatter bugs that you discover.

Then, make sure to also manually verify that the confirmation e-mail and PDF are properly formatted.

**Tasks**

- [ ] Update/extend Formio fixtures for tests
- [ ] Ensure tests are expanded/updated and passing with the feature flag disabled
- [ ] De-duplicate the `openforms.registrations.camunda.contrib.tests.files` fixtures (use the `openforms.formio.formatters.tests.files` fixtures instead)
- [ ] Update the tests to enable the feature flag
    - [ ] Fix any Formio formatters bugs you encounter
- [ ] Manually test the formatting of all components
    - [ ] Confirmation PDF
    - [ ] Confirmation e-mail
    - [ ] Summary (SDK)
