### ISSUE TITLE
Admin Form builder shows ambiguous error if user has been logged out

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1308]
Whenever I am editing a form in the admin and I take too long, when I try to save I get the error:

![Screenshot from 2022-02-07 15-04-19](https://user-images.githubusercontent.com/19154114/152803226-6b6afbb6-301a-403a-8109-4abd3a8327c7.png)

While in the console it shows that the PUT to `/api/v1/forms/<form-uuid>` returns a 401 not authenticated response.

**Tasks**

- [x] Show a proper/clear error if an HTTP 401 is returned instead of the generic error
- [x] Display a timer indicating how long/when the session expires. We can use the `X-Session-Expires-In` response header like in the SDK
- [x] Show a modal if the session is close to expire with the option to extend the session
    - [x] Implement an `/api/v1/ping` endpoint for this purpose (require authenticated user or active submission session users), response is HTTP 204
