### ISSUE TITLE
Make sure all plugins from the configuration overview behave properly

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1320]
The plugin overview uses very theoritical responses to check whether a connection can be made or not. Various fixes need to be done to make this work at all. This ticket is about the "Configuration overview" page.

**Tasks**

* [x] Only show and call `check_config` for plugins if they are enabled in the General settings (see screenshot 1). This should clean up the list and make the page faster to load.
* [x] StUF-ZDS cannot work with a fake BSN (causes upstream issues). This check should be refactored to only do a connection/ssl test or retrieve the WSDL if possible.
* [x] Haal Centraal, same reason, refactor to do a GET-requests that is invalid to simple check the connection/ssl
* [x] KvK registration plugin uses the wrong GET-request. Use the proper one (Basisprofiel API)
* [x] Refactor the the view to show only the error message: "Failed to validate the configuration." in case of an error. In the alt/title attribute, you can put the whole error. This should clean up the view.

Screenshot 1:
![image](https://user-images.githubusercontent.com/96970/178470847-b6cd39f6-9c79-48cf-8d99-f2060c847ab0.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/96970/178471224-db8a422c-1b01-4769-bf17-f5aadbb7839a.png)
