### ISSUE TITLE
Implement extension mechanism

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1336]
### Module system

Open Forms ("the backend") is implemented with a pluggable architecture. The
documentation is lagging behind a bit, but in essence there are modules focusing around
a class of functionality within Open Forms. This functionality can be implemented in a
variety of ways, using (different) vendors. Open Forms implements these as plugins
within the module.

At the time of writing, the following modules exist:

* registrations
* authentication
* prefill
* payments
* appointments
* formio formatters
* formio custom types
* validations

Modules and plugins are Python packages with some Django bindings. They are called
by the Open Forms core functionality (forms, submissions...)

### Extending

We want to support two flavours of extensions, where extensions are new plugins within
existing modules. This could be implementing the bindings with an alternative vendor
currently not supported.

1. Extensions in Open Forms itself that serve the greater community. These can be
   contributed as a pull request to Open Forms.

2. (Possibly closed source) organization-specific extensions. Some extensions are so
   extremely specific or can't be open sourced. This class of extensions is what this
   design document is about.

If the desired extension does not fit within existing modules, then integration of the
module needs to be done in Open Forms core first, which is out of the scope of this
issue.

For the scope of this issue, we also initially focus on backend extensions. A future
design document will deal with extending the Formio.js javascript functionality.

## Acceptance criteria

* Extensions can be developed indepedently from the open-formulieren Github organization
* Extensions can be developed as closed source (TODO: check if the EUPL-1.2 license says
  something about that)
* Extensions can be deployed with a stable Open Forms release
* Forking of Open Forms is not required and even discouraged

## Downstream usage

The goal is to modify Open Forms in such a way that it can be used as a base to extend
without having to maintain a fork of Open Forms.

Extension code can be "deployed" in two ways:

* building a custom docker image based on the upstream Open Forms image and adding the
  extension code (preferred)
* keeping the extension code in a volume and mounting it at container runtime

Extension code should be loaded/bootstrapped through a deployment-time environment
variable specifying which extensions to load.

### Extension as Django package

An extension must be implement as a Django package, which is a stricter form of a
regular Python package.

Extension code is allowed to import from Open Forms' public API, as documented on
https://open-forms.readthedocs.io/en/latest/developers/backend/core/index.html

Extensions cannot require modifications to Django settings. Any run-time configuration
options can be specified as:

* deployment time environment variables, for which the `openforms.conf.utils.config`
  helper is available
* dynamic options using `django-solo`, with the advantage that configuration can be
  modified at runtime

If any initialization or module loading is needed, this should be done as part of the
extension's `extension.apps.ExtensionConfig.ready` hook, which is called when django
bootstraps. This is the mechanism to register extra plugins for existing modules,
see also https://open-forms.readthedocs.io/en/latest/developers/plugins/index.html.

### Source code distribution/packaging

To be able to load the extension python package, it must be available in the python
path.

Candidates are:

* a package under the `src` directory (`/app/src` in docker image), automatically picked up
* a package anywhere in the file system, picked up by modifying the `PYTHONPATH`
  envvar by adding the (mount) path
* a package under the relevant `site-packages` directory
  (`/usr/local/lib/python3.8/site-packages/'` in the docker image), mimicking `pip install`
  / virtualenv. Automatically picked up.

You can either use a custom Dockerfile extending from the stable Open Forms releases,
add the extension source code in the desired location and build a custom image, or
mount the source code as a volume. On a development environment, you should be able
to use symlinks.

### Environment variable

One or multiple extensions must be supported, and enabling them is done through the
`OPEN_FORMS_EXTENSIONS` environment variable. The variable is a comma-separated list
of valid python identifiers (i.e. the python package names).

Example value: `my_org.registrations.plugins.vendor_a,open_forms_contrib`

The Open Forms `base.py` settings module must extract this configuration value and
append the list of packages to `INSTALLED_APPS`, which causes them to be loaded by
Django. This also ensures that `migrate` will run any necessary migrations.

### Documentation

The extension deployment mechanism must be documented under
`docs/developers/extending.rst`, with pointers to relevant documentation sections (for
developers) and information for devops roles (how to extend the Open Forms backend image,
how to deploy extensions at runtime...).

### CI

A demo extension should be implemented and tested in CI as a separate Github Workflow,
demonstrating the principles and testing that the mechanism works and keeps working.

Preferable we use a custom Dockerfile extending the base Open Forms image.

## Tasks

- [ ] Implement `OPEN_FORMS_EXTENSIONS` envvar.
- [ ] Developer and devops documentation added
- [ ] Create demo extension
- [ ] Test mechanism in CI

**Comment by sergei-maertens** [comment]
The principle itself has been tried out before in https://github.com/VNG-Realisatie/documenten-api/blob/master/src/drc/conf/base.py#L9 :-)

**Comment by SilviaAmAm** [comment]
Env var and documentation PR: https://github.com/open-formulieren/open-forms/pull/1353/files
Demo extension https://github.com/open-formulieren/demo-extension

**Comment by alextreme** [comment]
@sjoerdie Silvia zal je morgen vragen of je haar hiermee kan assisteren
