### ISSUE TITLE
Make file-uploads-as-attachment configurable on the registration backend.

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1363]
Taiga 411

#1193 changed the behaviour for the e-mail registration backend to no longer include file-uploads as attachments (for good reasons!).

However, this poses problems for some users of Open Forms, so we should make this behaviour configurable. The default should be the current situation (no mail attachments), while the registration backend must get an opt-in to use attachments instead.

**Tasks**

- [x] Add e-mail registration backend option to attach file uploads (default False)
- [x] Ensure that the files are added as attachments in those situations
- [x] Set up global default + form-override (must be `NullBooleanField` to discern between False/unset)
