### ISSUE TITLE
NL Design System integration

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1512]
Following the initial work by Bryan for NL Design System integration in https://github.com/open-formulieren/open-forms-sdk/pull/187, we've evaluated the direction and next steps to move into. This issue is more of an epic to track the individual subtasks. Initially we scope this to the SDK only, in the future we might also tackle the backend project.

**Acceptance criteria**

The general acceptance criteria to define a succesful NL DS integration.

* Excellent documentation for Open Forms SDK developers to get started and comfortable with NL Design System
* Implementation/replacement of components with existing NL Design System components
* Accessibility issues resolved
* Theme switcher
* New NL DS Theme for the current (before NL DS) look and feel of Open Forms SDK
* Pluggable and flexible Open Forms SDK package available on NPM for "power users"

**Tasks**

These are the high level tasks with more implementation details in each referenced user story.

- [ ] Organize periodic (monthly, weekly?) sessions with the SDK and NL DS development teams (~30 min max)
- [ ] Use CSS variables rather than SASS variables, as this is the principle NL DS themes operate on
- [ ] Get parts of the existing work merged (e.g. radio component)
- [ ] Publish the SDK as a library/package to npmjs.com (`@open-forms/sdk` ?), exposing the underlying React components
- [ ] Add support for pluggable components, such as the progress indicator
- [ ] Add support for layout customizations, such as headers/footers
- [ ] Compile a list of accessibility issues and fix them
