### ISSUE TITLE
Use CSS variables rather than SASS variables for colors, as this is the principle NL DS themes operate on

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1514]
The SDK is mostly parametrized using sass variables: https://github.com/open-formulieren/open-forms-sdk/blob/main/src/scss/_settings.scss

These variables are used throughout https://github.com/maykinmedia/microscope-sass, whose sass mixins are used frequently throughout the codebase. One major issue is that these library mixins often use sass functions like `darken`/`lighten` based on the sass variable values or mathematical operations like `$some-dimension * 2`, which is not compatible with CSS variables. Earlier efforts to define the colors as CSS vars rather than sass vars failed because of this.

**Tasks**

- [x] Check and update microscope-sass so that for every implicitly calculated value and explicit value can be specified, which may in turn be a CSS variable (e.g. `@include mymixin($color: var(--some-color));`)
- [x] SDK: replace usage of sass vars with css vars
- [x] Include `:root` CSS rule defining all the default values for variables (as far as these aren't defined by NL DS)

**Comment by sergei-maertens** [comment]
I checked microscope-sass and couldn't find any calls to `lighten` or `darken` in there, so could be that all those calls are actually contained in open-forms-sdk already.

**Comment by sergei-maertens** [comment]
Colors are done
