### ISSUE TITLE
Publish the SDK as a library/package to npmjs.com

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1516]
Possible name: `@open-forms/sdk`

The idea is that we publish the package and underlying components to NPM so that downstream users can build their own layout/wrapper and configure in more detail what they need.

**Tasks**

- [x] Configure webpack config (or other bundler?) to emit a package suitable for publishing
- [x] Set up CI account/credentials on npmjs for Open Forms
- [x] Set up CI action(s) to build and publish the package for tagged releases (similar to Docker image build)
- [x] Determine, expose and document the public API/Components
- [ ] Give storybook/Docusaurus a go for documentation?

**Comment by sergei-maertens** [comment]
CI now publishes tagged versions as an NPM package too: https://github.com/open-formulieren/open-forms-sdk/runs/7406839029?check_suite_focus=true

And the package on NPM: https://www.npmjs.com/package/@open-formulieren/sdk
