### ISSUE TITLE
Set up SDK documentation with links to NL DS resources

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1521]
For good adaption and to encourage best practices, it should be as easy as possible to get started with NL DS. To achieve this, the documentation needs to provide the right pointers.

**Tasks**

- [x] Update SDK developer documentation with introduction, vision and links to related resources
    - Point to general NL DS documentation
    - Point to getting-started guide for NL DS
    - Document how Open Forms SDK uses NL DS and what the development flow looks like
- [x] Update README/CONTRIBUTING of SDK to point to NL DS and SDK developer documentation on readthedocs
- [x] Set up Storybook for component development/documentation (and use github pages to publish it?)
