### ISSUE TITLE
Convert JSON-schema to generate form

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1673]
### Thema / Theme

Other

### Omschrijving / Description

As a utility for now, I want to convert a JSON-schema to Form.IO JSON.

In essence, this:

```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "required": [
      "kenteken",
      "postcode",
      "huisnummer"
    ],
    "title": "Het objecttype Melding Openbare Ruimte",
    "properties": {
      "kenteken": {
        "title": "Kenteken",
        "type": "string",
        "pattern": "^[A-Z0-9][A-Z0-9]?[A-Z0-9]?-[A-Z0-9][A-Z0-9]?[A-Z0-9]?-[A-Z0-9][A-Z0-9]?[A-Z0-9]?$",
        "description": "Kenteken van het voertuig waarvoor de aanvraag wordt gedaan.",
        "examples": [
          "XX-11-YY"
        ]
      }
    }
}
```

Should be converted to this:

```json
{
    "components": [
        {
            "label": "Kenteken",
            "description": "Kenteken van het voertuig waarvoor de aanvraag wordt gedaan.",
            "tableView": true,
            "validate": {
                "required": true,
                "pattern": "^[A-Z0-9][A-Z0-9]?[A-Z0-9]?-[A-Z0-9][A-Z0-9]?[A-Z0-9]?-[A-Z0-9][A-Z0-9]?[A-Z0-9]?$"
            },
            "key": "kenteken",
            "type": "textfield",
            "input": true
        },
     ]
}
```

You can find a JSON schema playground here: https://www.jsonschemavalidator.net/
JSON schema explanation here: 
The validation checks are explained here: https://json-schema.org/draft/2020-12/json-schema-validation.html (see chapter 6 and 7.3)
Form.IO playground: https://formio.github.io/formio.js/app/builder

**Tasks**

* [ ] Create function `convertJsonSchema2FormIO(json_schema)` and have it return a (FormIO) JSON string
* [ ] Add support for `properties.[key]` -> `key`
* [ ] Add support for `properties.[key].title` -> `label`
* [ ] Add support for `properties.[key].description` -> `description`
* [ ] Add support for `properties.[key].default` -> `defaultValue`
* [ ] Add support for `properties.[key].pattern` -> `validate.pattern`
* [ ] Add support for `required.[key] -> `validate.required`
* [ ] Add support for `properties.[key].type + `properties.[key].format` -> `type` (see schema validation section 7.3 and match them as best as you can to FormIO components)
* [ ] Add support for other validations that can be in JSON-schema (see section 6 EXCEPT FOR objects) - like minLength, maxItems, etc.

### Added value / Toegevoegde waarde

This allows us in the future to import ProductAanvraag Objecttypes and generate the basic form.
