### ISSUE TITLE
SDK progresses to next step even if step submit returns HTTP 400

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1687]
That should not happen - validation errors should be properly displayed & step progression blocked.

**Tasks**

- [x] Add backend validate endpoint for the SDK to call (https://github.com/open-formulieren/open-forms/pull/1690)
- [ ] Bump API version in backend for patch releases (1.0.x, 1.1.x) and document the SDK version requirement.
- [x] Process the validation errors client-side so they're displayed with the relevant component (https://github.com/open-formulieren/open-forms-sdk/pull/210)
