### ISSUE TITLE
Interface to handle inserting variables in Formio configuration

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1708]
### Thema / Theme

Other

### Omschrijving / Description

Comment referring to this feature: https://github.com/open-formulieren/open-forms/pull/1647#discussion_r886544587

There needs to come a way to inject variables into the:
- label of certain components
- the html of content components
- the default value of components: (see Taiga DH issue 54, user story 114)

**Tasks**

- [x] Profile how the templating solution performs
- [x] depending on profiling results, investigate optimization paths

**Implementation**

- [x] Implement templating component properties
- [x] Implement form designer validation for template syntax errors

**Extra**

Probably split this in different ticket

- [ ] #1900
- [ ] #1902
- [ ] Variables in min / max configuration of date field: #1878

**Comment by sergei-maertens** [comment]
Some technical analysis of what the options are. Feel free to add suggestions/remarks.

## Constraints

**Simple variables**

- `now` -> datetime (python datatype) or ISO-8601 string (for display)
- `someKey`: `123`
- `someKey`: `123.45`
- `someKey`: `"foo"`
- `someKey`: `None`
- `someKey`: `False`

-> value is always a JSON primitive: `null`, `string`, `number`, `boolean`.

**Complex variabeles**

- `someKey`: `{"foo": {"bar": "baz"}}`
- `someKey`: `["foo, "bar"]`

## What exists?

Check for existing tools to avoid re-inventing the wheel

**JQ**

URL: https://stedolan.github.io/jq/manual/

* also used in Zaken API 1.2, fits ecosystem.
* well-known for people dealing with JSON on the CLI
* https://pypi.org/project/jq/ - Python bindings exist
* originally CLI only, so really meant for parsing strings into powerful expressions
* To figure out: extensible or not?
* Supports some built in operators/functions

**glom**

URL: https://glom.readthedocs.io/en/latest/

* already used throughout the codebase
* you can do a lot with simple string specs, but might need python-level access for
  complex operations -> limited for use in formio?
* To figure out: extensible or not?

**json logic**

URL: https://jsonlogic.com/operations.html

* used for logic & actions already, single "expression language"
* very verbose
* not sure how to get an editor for json logic into formio form builder
* not sure how to display this in "human readable" format
* definitely extensible!

**jinja2**

URL: https://palletsprojects.com/p/jinja/

* Similar to Django template language
* Exposes more direct python acess though...
* extensible
* [sandbox mode](https://jinja.palletsprojects.com/en/3.1.x/sandbox/)
* performant (allegedly)

**Django template language**

* Flexibile
* Lots of builtins
* No sandbox mode
* Extensible

## What do we want to support?

**Text-based component properties**

Think label, help-text, Content HTML...

In these components, we only want to get the string representation of variables, not the
raw underlying value.

This implies that the value has to go through the formatter before interpolating it
in "templates" (whatever templates may be), using
`openforms.formio.formatters.service.format_value`. This also means that we need
sufficient metadata for variables that are NOT component bound, or implement this
another way.

Proposed API: `variable.format_value()`, which then figures out what to call.

**Value-based component properties**

Such as `defaultValue`, maybe at some point we can even control booleans like `hidden`
through variables?

These should use the raw underlying value, but make sure to type-cast to the correct
type if Formio can't handle with mismatching types. It should be fairly simple, since
it's JSON anyway.

**Calculations**

No inline calculations, so no things like `You are {{ (now - dateOfBirth)|years }}`-like
constructions.

We should facilitate calculating values (on the fly?) as part of the logic/variables
tab for which we can use JsonLogic expressions.

To keep the Formio integration simple, we only support outputting a single variable,
optionally applying some formatting.

**Recursion**

There is a chance (when we will support i18n) that we need to store a label inside a
variable, but that in itself contains references to variables. So, possibly we need
recursive evaluation and the chosen solution will have to support that. This possibly
conflicts a bit with the "no calculations" principle.

## Possible syntaxes (focusing on labels)

Given input data:

```json
{
    "age": 33,
    "partner": {"firstName": "Dormammu", "lastName": "Destroyer of Worlds"},
    "children": [
        {
            "firstName": "Kaecilius"
        }
    ]
}
```

We consider 4 situations trying to output dynamic labels:

- Confirm that you are 33 years old
- Details of your partner Dormammu Destroyer of Worlds
- Please provide details about your 1 child(ren)

Repeating group, for index 0:

- Your child Kaecilius

**JQ**

- `Confirm that you are {{ age . }} years old`
- `Details of your partner {{ partner .firstName }} {{ partner .lastName }}`
- `Please provide details about your {{ children length }} child(ren)`

Repeating group where we fill out the index (presumably)

- `Your child {{ children .[$index].firstName }}`

-> for use in string templates, we still need to wrap it in curly braces (or another
construct) to make it clear what the variable is, and which part is the JQ expression.

**glom**

- `Confirm that you are {{ age }} years old`
- `Details of your partner {{ partner firstName }} {{ partner lastName }}`
- ?? no idea how to get counts with a simple glom expression

Repeating group where we fill out the index (presumably)

- ??

-> for use in string templates, we still need to wrap it in curly braces (or another
construct) to make it clear what the variable is and which part the glom expression.
It's also immediately clear that string-only specs are not enough for glom.

**json logic**

- `Confirm that you are $({"var": "age"}} years old`
- `Details of your partner $({"var": "partner.firstName"}) $({"var": "partner.lastName"})`
- `Please provide details about your $({"length": {"var": "children"}}) child(ren)`

Repeating group where we fill out the index (presumably)

- `Your child $({"var": "children.$index.firstName"})`

In this case, the `length` operation should be implemented as a custom operator. It's a
bit verbose, and we need a wrapper so that we can parse the `json` expression for the
logic.

The repeated `var` key every time is also a bit verbose and shouldn't necessarily be
needed?

**jinja2**

- `Confirm that you are {{ age }} years old`
- `Details of your partner {{ partner.firstName }} {{ partner.lastName }}`
- `Please provide details about your {{ children|length }} child(ren)`

Repeating group where we fill out the index (presumably)

- `Your child {{ children[$index].firstName }}`

Pretty natural, and gives access to template filters. We might want to block template
tags though, but then again, those could be useful in Content HTML blobs. jinja2 may
be a footgun, so it's a matter of documenting what we do and don't support?

**Django template language**

- `Confirm that you are {{ age }} years old`
- `Details of your partner {{ partner.firstName }} {{ partner.lastName }}`
- `Please provide details about your {{ children|length }} child(ren)`

Repeating group where we fill out the index (presumably)

- `Your child {{ children.$index.firstName }}`

Requires pre-processing of the template expression to bake in the index, otherwise
similar remarks as jinja2.

## WYSIWYG and markup copying

WYSIWYG is tricky in itself, since the expressions should copy the embedded markup. With
loops this may be a challenge.

TODO: figure this out later.

**Comment by SilviaAmAm** [comment]
I was thinking that in [formio.service.insert_variables](https://github.com/open-formulieren/open-forms/blob/8ffc3eb250ec3be550fd25ddc21165c8be2a2a3b/src/openforms/formio/service.py#L49) we could have:
```
formatted_variables = value_variables_state.get_formatted_variables(request)
```

The variables have a `data_type` attribute, which is enough to format "simple variables", but for things like `selectboxes` we would need more info stored on the variable to be able to format it without looking for the component. 
So not sure if it would be best to add a field to the variable where we store this info (and then we can just use the formio formatters), or if we should add metadata on how to format complex fields (selectboxes, files, maps, ...).

Also we will have to think about performance, since if we use this in `get_dynamic_configuration` it will run on every `_check_logic` call

**Comment by sergei-maertens** [comment]
Optimization paths:

* on save, post-process the form definition and extract what needs to be templated out (and store that), so that we only process components containing variables/template expressions. We could use the template parser/lexer for that
* Maybe store the pre-compiled templates somewhere, so we can skip the parsing/lexing step? That would probably rely on the `pickle` module though.
* threading is unlikely to have any effect, since there's no IO being done - this should all be CPU
* multiprocessing seems like a footgun, but could be a last resort? not sure what the start-up penalty is though
