### ISSUE TITLE
Additional static variables

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1711]
### Thema / Theme

Other

### Omschrijving / Description

DH Taiga issue 107

The list of desired new variables is:
- Date of today (with various formats like 6/23/2022 or vrijdag 10 maart 2006)
- Current month
- Current day
- Current Year
- OTAP: the name of the environment. Should be Test, Acceptation or Production. This can leverage the setting `settings.ENVIRONMENT`.
- Current month name (tbd if in english or dutch)
- Current day name
- Current time (with varying formats, like 12:33, 12:33:26)
- Current week number
- Form Name
- Form ID

**Comment by SilviaAmAm** [comment]
Need to clarify why all these different formats are needed. Is it for displaying or for calculating things?

**Comment by sergei-maertens** [comment]
With the implementation #1869 of #1708 we've settled on using (a sandboxed version of) the django template engine. This exposes the built in template tags and filters, so they can use the date/time formatters for all the display variations of "current timestamp". That tackles most of the extra requested variables, turning this ticket mostly into a documentation issue.

- [ ] Document support for built in template tags/filters for form designers
    - Link to Django (3.2!) built in template filters/tags documentation
    - Provide a number of examples of date formats for the requested "now" variations in a table (column template bit -> column resulting value) so there's an easy lookup table. Perhaps include a column with the description as in this ticket as well.
- [ ] OTAP: add `settings.ENVIRONMENT` as a static variable once #1825 is merged
- [ ] Form name: add as static variable once #1825 is merged (use the submissions app, not the forms app!)
- [ ] Form ID (UUID?): add as static variable once #1825 is merged (use the submissions app, not the forms app!)

**Comment by sergei-maertens** [comment]
we'll hear feedback if it's not good what we did/do, but it seems like we're not getting any refinement soon
