### ISSUE TITLE
Add support for Piwik Pro

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1716]
### Thema / Theme

Admin

### Omschrijving / Description

We support Google Analytics, Matomo, and others. We also need to support Piwik Pro (not to be confused with Piwik!)

See: [Instructie GTM en Piwik Pro instaleren op nieuwe website.docx](https://github.com/open-formulieren/open-forms/files/8990616/Instructie.GTM.en.Piwik.Pro.instaleren.op.nieuwe.website.docx)

Source: DH Taiga 100

**Tasks**

* [x] Add snippet to frontend
* [x] Add support in the admin
* [x] Document support for Piwik Pro
* [x] Document the URLs that need to be whitelisted in CSP config

### Added value / Toegevoegde waarde

More anyalitcs support.
