### ISSUE TITLE
Import a Product from the PDC API to generate the basic form

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1734]
### Thema / Theme

Admin

### Omschrijving / Description

With the upcomming PDC API featuring Products with a ProductAanvraag containing a JSON schema, we can link a form to a Product. However, the PDC API is not done and there's more feature that are usefull when linking product.

So, for now, we just want to import a JSON schema, which will generate a basic Open Forms form!

**Tasks**

* [ ] Continue on code in ...
* [ ] Add a button "Import Product" to the Product page in the Open Forms admin
* [ ] Add view for the Import Product page to select a JSON-schema file.
* [ ] Once the JSON-schema is imported, the result should be a Open Forms form instance with 1 step, containing all fields that are in the JSON-schema. The form name can be the title from the JSON-schema and the step name can be "Product velden".

**Comment by joeribekker** [comment]
Example schema:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "required": [
    "kenteken",
    "postcode",
    "reden",
    "huisnummer"
  ],
  "title": "Het objecttype Melding Openbare Ruimte",
  "properties": {
    "kenteken": {
      "title": "Kenteken",
      "type": "string",
      "pattern": "^[A-Z0-9][A-Z0-9]?[A-Z0-9]?-[A-Z0-9][A-Z0-9]?[A-Z0-9]?-[A-Z0-9][A-Z0-9]?[A-Z0-9]?$",
      "description": "Kenteken van het voertuig waarvoor de aanvraag wordt gedaan.",
      "examples": [
        "XX-11-YY"
      ]
    },
    "reden": {
      "title": "Reden",
      "type": "string",
      "description": "Reden van deze aanvraag.",
      "examples": [
        "Parkeren bij werk"
      ],
      "enum": [
        "Parkeren bij werk",
        "Parkeren bij woning",
        "Parkeren voor ondersteuning/verzorging"
      ]
    },
    "redenToelichting": {
      "title": "Reden toelichting",
      "type": "string",
      "maxLength": 1000,
      "description": "Licht uw reden toe.",
      "examples": [
        "Parkeren bij werk"
      ]
    },
    "postcode": {
      "title": "Postcode",
      "type": "string",
      "pattern": "^[0-9]{4}[A-Z]{2}$",
      "description": "Postcode van het adres waar het voertuig het dichtst bij in de buurt geparkeerd wordt.",
      "examples": [
        "1000AB"
      ]
    },
    "huisnummer": {
      "title": "Huisnummer",
      "type": "integer",
      "description": "Huisnummer van het adres waar het voertuig het dichtst bij in de buurt geparkeerd wordt.",
      "examples": [
        "1000AB"
      ]
    }
  },
  "additionalProperties": false
}
```
