### ISSUE TITLE
Display logic rules nicely

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1751]
Logic rules in the core are based on JSON-logic. With the admin (simple logic rules) we allow them to be clicked together, and it automatically creates a pretty printish format. This doesn't work for advanced logic.

**Example**

In humanized form (ie. someone actually typed this as a title or something):

*You are male, 18 years or older and the average income of you and your partner is equal or higher than EUR 35.000*

In JSON-logic:

```
{ "and" : [
  { "==": [{ "var": "gender" }, "m"]},
  { ">=": [{ "var": "age" }, 18]},
  { ">=" : [
    {"/": [
      {"+": [
        { "var": "yourIncome" },
        { "var": "partnerIncome" }
      ]},
      2
    ]},
    35000
  ] }
] }
```

Automated "humanized" form:

**gender** *=* **m** *and* **age** *>=* **18** *and* ( ( **yourIncome** *+* **partnerIncome** ) */* **2** *>=* **35000** )

**Tasks**

* [x] Create function to generate automated humanized form from JSON-logic
* [x] Use this function in the logic logging for simple and advanced rules
* [x] Create and use a similar function (or the same?) for actions
