### ISSUE TITLE
Het formulier toont per stap / pagina / sectie een eenvoudige, gebruiksvriendelijke, unieke en toegankelijke URL ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#178]
...in de adresbalk van de gebruikte internetbrowser. Ook de stappen voor én na het inloggen met alle beschikbare identificatie- en authenticatiemiddelen kennen een unieke URL. De unieke URL is meetbaar in gangbare statistiekprogramma's zoals Siteimprove, Matomo, Piwik en Google Analytics.

Eis: Algemeen 4.
Zie ook NvI: 131

**Intern overleg**
Gebruik van React Routes
```
https://formulieren.gemeente.nl/[formulier slug]/[stap slug]

# Voorbeeld
https://formulieren.gemeente.nl/uittreksel-brp/uw-gegevens
```

**Tasks**

- [x] Set up React router
- [x] Ensure React router uses the current location as base URL
- [x] Each form step is driven by a sub-url (based on the slug)
- [x] Ensure pluggable support for statistic programs is set up (GA, Piwik...)
    - [x] Ensure every navigation is emitted as page visit (abstracted)
