### ISSUE TITLE
Een gebruiker van de toepassing kan zonder tussenkomst van de leverancier een voortgangsbalk laten tonen. Deze ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#179]
...kan worden getoond in minimaal de variaties: niet (geen voortgangsbalk), percentage van het totaal én titels van de stappen / pagina's en secties.

Eis: Algemeen 5.
Zie ook NvI: 132

**Tasks**

- [x] Add admin pulldown to choose progress indicator: 1) None, ~2) Percentage~, 3) Steps
- [x] Add this progress indicator to the API spec
- [x] Add frontend interface to reflect the choice made here.
- [ ] Add "(n.v.t.)" to the step title whenever a step is not needed due to decisions/logic -- depends on #183 
- [x] Create design for mobile steps
- [x] Apply design for mobile steps to UI

**Verduidelijking**

Percentage in overleg is vervallen. Stappen die niet ingevuld hoeven te worden voorzien van "(niet van toepassing)".

**Mobile design**

<img src="https://user-images.githubusercontent.com/96970/125066505-5aad3280-e0b3-11eb-86da-8a1260e091f3.png" width="300"> <img src="https://user-images.githubusercontent.com/96970/125066494-584ad880-e0b3-11eb-8022-a72236702394.png" width="300">
