### ISSUE TITLE
Een gebruiker van de toepassing kan zonder tussenkomst van de leverancier een trackingscode toevoegen van een ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#181]
...statistiekprogramma. Dit zijn minimaal Siteimprove, Matomo, Piwik en Google Analytics. Daarbij kan de cookiemelding worden in- of uitgeschakeld. Als de melding wordt uiteschakeld, wordt de data alsnog direct verzameld.

Eis: Algemeen 7.
Zie ook NvI: 134

**Tasks**

- [x] Add option to enter various tracking codes
- [x] Add templates for each provider, included on the form detail page
- [x] cookiemelding?

**Verduidelijking van Gemeente nodig**

- [x] Hoe moet het frame er een beetje uit zien van een "blanco" gemeente pagina waarin het formulier komt?
- [x] Welke melding moet in de cookiemelding?
- [ ] Graag voorbeelden geven van snippets voor SiteImprove, Matomo, Piwik

**Comment by sergei-maertens** [comment]
2 features:

- [ ] Logo uploaden
- [ ] Linkje invullen voor "terug naar gemeentewebsite"
