### ISSUE TITLE
Een gebruiker van de toepassing kan zonder tussenkomst van de leverancier logica toekennen aan een element of ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#183]
...veld op basis van data en getallen. Dat betekent per veld of selectie van velden: een minimale en / of maximale negatieve en positieve waarde in getallen tot 2 cijfers achter de komma, een bereik in data (bijvoorbeeld x periode in dagen of weken vooruit of achteruit in de tijd en tijdstippen die aan elkaar gerelateerd kunnen worden. Indien niet wordt voldaan aan de logica verschijnt een voor de inwoner of ondernemer duidelijke melding in beeld waarin de verwachtte waarde wordt weergegeven.

Eis: Algemeen 9.
Zie ook NvI: 9, 47, 66

**Verduidelijking**

Heeft te maken met... vergunning aanvragen, dan moet aanvraagdatum bijv. tussen bepaalde data liggen. Ik zoek een paar voorbeelden van wat mogelijk moet zijn (velden die met elkaar praten). Datum velden die aan elkaar gekoppeld zijn.

Bespreek met Heda na 14 juli.

**Tasks**

- [x] Add "(n.v.t.)" to the step title whenever a step is not needed due to decisions/logic (progress indicator in SDK, split off from #179)
* [x] Datum voor/na/op datum
* [x] Datum x is maximaal +y van datum z
* [x] Tekst bevat/is

**Comment by sergei-maertens** [comment]
Hidden input in form design -> on condition: show hidden input. The hidden input then contains an error message for example (and the next-button can be disabled).
