### ISSUE TITLE
Een gebruiker van de toepassing kan zonder tussenkomst van de leverancier de toepassing uitgebreide berekeningen ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#184]
...laten maken én de uitkomst hiervan tonen aan de inwoner en ondernemer én in de definitieve inzending. Voorbeelden hierbij zijn situaties van kilometerregistraties en indienen van vergoedingen (deze eis valt buiten het MVP).

Eis: Algemeen 10.
Zie ook NvI: 10, 67

**Tasks**

* [x] In the logic tab, add a new button to add an advanced rule: "Geavanceerde regel toevoegen"
* [x] An advanced rule is a textarea where a JSON-logic expression can be entered manually.
* [x] Validation should be done on the manually entered JSON-logic expression.
* [x] An advanced rule is simply shown as JSON-logic, no UI is shown.

**Comment by joeribekker** [comment]
We hebben meer uitputtende voorbeelden nodig.

**Comment by BasvanRensDK** [comment]
@Hedda-van-Ooijen @Dorhout komen met een reactie

**Comment by elkpl** [comment]
Bij ons gaat het vooral om de volgende functionaliteit:
We organiseren bijv. een bijeenkomst met 3 sessies. Hiervoor maken we een aanmeldformulier waarbij mensen een sessie kunnen kiezen. Bij iedere sessie mogen maximaal 20 aanmeldingen zijn. Als die 20 bereikt zijn, dan moet er een tekst getoond kunnen worden a la ‘Deze sessie is vol. Kies een andere sessie. ‘ Hierbij kijkt het formulier dus bij eerdere aanmeldingen om de berekening te maken hoeveel aanmeldingen er zijn totaal.
Het systeem moet kunnen omgaan met het feit dat mensen in het formulier kunnen aangeven met hoeveel personen ze komen. Daarom kunnen we dit ook niet oplossen met het beperken van het aantal inzendingen op 20 (in dit voorbeeld).

**Comment by Dorhout** [comment]
Bijvoorbeeld:
Inkomstenopgaveformulier.
Een optelling kunnen maken van een aantal velden.
vraag 1 1000,00
vraag 2   300,00
vraag 3   100,00
vraag 4   200,00
Totaal   1600,00

Bijvoorbeeld berekening netto omzet
Bent u een BV  = ja
Omzet               1000,00
Vaste lasten        300,00
dga                       50,00
Netto omzet deze wordt als volgt berekend als het een BV = ja
Als Omzet - vaste lasten > 0 dan omzet - vaste lasten * 85/100 + dga
Als Omzet - vaste lasten < 0 maar als Omzet - vaste lasten + dga >0 dan Omzet - vaste lasten + dga
anders 0

Als bv = nee
Als omzet - vaste lasten >0 dan omzet - vaste lasten * 82/100 anders 0

Voor bovenstaande berekeningen gebruik ik (in de Exxellence Suite) de functie valideer waarde waarin op basis van condities de berekeningen worden gemaakt.
Voor de BV ziet dat er zo uit.

[Omzet] - [VasteLasten] >0 && "{flowData|periode.form.bv}" =="ja" ? ([Omzet] - [VasteLasten]) * 85/100 + [dga] : ([Omzet] - [VasteLasten] <0) && ([Omzet] - [VasteLasten] + [dga]  >0) && "{flowData|periode.form.bv}" =="ja" ? ([Omzet] - [VasteLasten]) + [dga] : 0

**Comment by joeribekker** [comment]
@elkpl Dit is een andere nieuwe feature want dit houdt iets centraals (over meerdere inzendingen) bij en gaat veel verder dan een berekening binnen een formulier.

@Dorhout Pittig, maar dit lijkt aan te sluiten op de eis. Wat we gaan doen is een "poweruser" feature inbouwen zodat je zelf de JSON-logic kan bewerken en dit soort berekeningen kan maken. Dit kan dan niet weergegeven worden in de grafische UI met "Als [pulldown] dan [actie]" maar stelt je wel in staat complexere dingen te doen.
