### ISSUE TITLE
Er worden extra (CSP) headers meegestuurd zodat de gebruikte internetbrowser de toepassing veilig kan renderen.

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#185]
Eis: Algemeen 11.

**Tasks**

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

* [x] Add `Content-Security-Policy` header to form-repo using Django CSP. For example: `Content-Security-Policy: default-src 'self'` (make sure to check if we don't load external sources somewhere, like js, css, icons, etc. in browser console).
* [ ] Add `Content-Security-Policy` header to SDK Nginx. For example: `Content-Security-Policy: default-src 'self'` (make sure this can reach the API endpoint) by maybe using `connect-src 'https://....'`
* [ ] We optionally allow loading external providers, Google Analytics, etc. These need to be permitted.
* [ ] Report violations to Sentry

**Comment by Bartvaderkin** [comment]
Does this specify what part of the application the requirement is about? Form builder, SDK or both?

The effect of these headers is controlled by whoever serves the HTML, which may not be us for SDK embeds.

Another complication is how CSP doesn't allow script tags, and enabling them defeats part of the CSP protection as there could still be script injection. https://content-security-policy.com/examples/allow-inline-script/
