### ISSUE TITLE
Allow employees to login to a form using OpenID-connect

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1861]
DH Taiga 95

**Tasks**

* [x] Add an Authentication plugin for OpenID-connect (this is VERY similar to: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/authentication/contrib/digid_eherkenning_oidc/plugin.py)
* [x] Make sure the plugin re-uses the general OpenID-connect configuration (the one under the Account menu settings in the admin).
* [x] Make sure we can configure a claim that holds the employee-number (much like the kvk-number in above linked code).
* [x] Make sure the employee number is saved on the form submission (much like how the bsn, kvk, pseudo id are saved at the moment). It should be hashed (or whatever is used for bsn, etc.)
* [x] Test the system as a whole against Azure AD and as an employee-number claim we can use the email (configured as mapping in the admin), since I'm sure you will get that.

**Comment by sergei-maertens** [comment]
> Make sure the employee number is saved on the form submission (much like how the bsn, kvk, pseudo id are saved at the moment). It should be hashed (or whatever is used for bsn, etc.)

For this, add a choice `employee_id` to `openforms.authentication.constants.AuthAttribute` and make sure that after successful authentication that value is properly stored via `openforms.authentication.utils.FormAuth`

**Comment by dariomory** [comment]
Discussed changes:
- User should be created after login is done in the form.
- Re-use `mozilla_django_oidc_db` views.
- Avoid extending `digid_eherkenning_oidc`.
