### ISSUE TITLE
Prepare release 2.0.0-beta

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1895]
First of, why 2.0.0 and not 1.2.0? We feel that the introduction of variables warrents a 2.0.0 version due to its massive overhaul of the core of Open Forms. We basically added an extra layer between the forms-frontend and the backend that allows for many interesting features that we added already and some that are yet to come. We also made an effort to make the migation path from 1.1.x to 2.0.0 silky smooth.

Why beta? Since we modified to core of Open Forms, we want to make an indication to users that this is most likely a version that will have some bugs that our QA missed.

**Tests**

- [ ] Test migration of forms: Import 20 forms from an in our 1.1.x test environment, migrate Open Forms on the test environment to 2.0.0-beta, and test if all forms work as intended.
- [ ] Test our test form
- [ ] Test creating new forms

**Tasks**

- [x] Remove API functionality that was deprecated in 1.x (#2046)
- [x] Remove deprecated action type 'value'
- [ ] Fix release blockers
    - [x] #1922
    - [x] Squash migrations (clean up old data migrations -> requires users to upgrade to the latest 1.x first and then to 2.x) (#2047)
    - [ ] #1979
        - [ ] Publish final 1.0.x version and mention support ended per our versioning policy
        - [ ] Publish 1.1.x version
    - [ ] Logic check -> must de-serialize input data appropriately
- [x] New SDK release (https://github.com/open-formulieren/open-forms-sdk/pull/235)
- [x] Correct SDK version pinned in `.sdk-release`
- [x] SDK translations checked and updated
- [x] Backend translations checked and updated
- [x] Check & update version number API
- [x] Bump version number (including package-lock.json)
- [x] Generate and update changelog
    - [x] Mention unique component key requirement & provide script to check this (has been run before on test environments!)
