### ISSUE TITLE
Implement setting the default value for non-string types (checkbox boolean)

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1900]
Split from #1708

In the above issue we can interpolate variables for text-based properties using the django template engine. However, ideally, for non-string based formio component types (checkbox, multiple checkboxes...) we want to be able to set other properties from variables.

This will require different/special handling (JsonLogic as engine for this seems appropriate?), since we need to maintain the relevant datatype - booleans in particular for checkboxes.

This may even be extended to be able to set all/most formio component properties from variable sources.

**Tasks**

- [ ] Update the form designer so that you can select an available (type-matching!) variable as data source for the `defaultValue` property
    - Allow users to select the source of the default value: "fixed value" or "from form variable"
    - When fixed value is selected -> keep the current behaviour
    - When from form variable is selected -> hide the current behaviour & show dropdown for variable selection
- [ ] Add data migration to update existing form definitions so that the `defaultValueSource` is properly set (so that editing forms is in the correct state)
- [ ] Save the variable reference as a JsonLogic expression
- [ ] Implement evaluating the expression as JsonLogic in the `openforms.formio.service.inject_variables` function
