### ISSUE TITLE
Een telefoonnummer element, waarbij een telefoonnummer op alle mogelijke maniere kan worden ingevuld. Dit is inclusief ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#200]
...vreemde tekens en spaties

Eis: Elementen 1l.
Zie ook NvI: 141

**Tasks**

* [x] Field should only allow numbers, dashes, spaces and + sign (as first char only). Either don't allow them as input, or raise validation error if present.

**Vragen voor gemeenten**

Uit de NvI:

> De kern van deze eis is dat het niet 'slechts' 1 denkbare invoerwijze is.

* [x] Is het voldoende dat we de volgende karakters toestaan: +, spatie, -, 0 t/m 9, en andere tekens niet toestaan?
* [x] Is het akkoord als we telefoonnumers niet normaliseren (dus alle mogelijke formaten proberen om te vormen tot 1 formaat)?
