### ISSUE TITLE
Een adres element waarbij aan de hand van de ingegeven postcode en huisnummer de straatnaam en plaats automatisch ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#201]
...worden gevuld.

Eis: Elementen 1m.
Zie ook NvI: 70, 142

**Verduidelijkt via gemeenten**

Moet uit BAG API komen.

**Tasks**

This prefill plugin prefills RUNTIME from the Javascript.

- [x] BAG API should be configurable in the Admin (api key + url)
- [x] ~~Add prefill plugin to use the configured BAG API~~
- [x] Add Open Forms API endpoint to accept: postcode, huisnummer
- [x] Open Forms should proxy the API request to the BAG API (I guess in the future, we can swap this for whatever)
- [x] The Open Forms API endpoint should return a streetname and a city (even if multiple results are returned, its always the same street+city, so just pick the first)
- [x] Add option in FormIO Builder in admin to set configuration for autofilling the street name and city
- [x] Add code in SDK to use proper configuration above to properly make the API request to the backend and autofill the street name and city
- [x] Add Form.IO stuff to make it work so we can: fill postalcode+number and then the fields street+city are prefilled.

**Comment by shea-maykinmedia** [comment]
@joeribekker I discussed creating the prefill plugin with @sergei-maertens and we decided not to use a plugin for this implementation since the plugin are made to be run when the form step is first loaded and not at runtime.
