### ISSUE TITLE
In een element is door een gebruiker het maximaal in te geven tekens in te stellen. De inwoner of onderemer ziet ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#210]
...dit weergegegeven in ene resterend aantal in te geven tekens (count-down). Het element groeit dynamisch mee. Dit betekent dat een veld met een maximale waarde van 1500 karakters tijdens het ingeven groeit en niet als één groot vlak zichtbaar vanaf het begin.

Eis: Elementen 1v.

**Tasks**

- [x] Put back "Show character count" feature in FormIO in Textarea and Textfield (see screenshot)
- [x] Put back "Auto Expand" feature in FormIO for Textarea (see screenshot)
- [x] Put back the max length feature in FormIO (validation tab) for Textarea and Textfield (see screenshot)

![image](https://user-images.githubusercontent.com/96970/123939614-9734ac00-d998-11eb-8ba6-1ad153e24c2d.png)
![image](https://user-images.githubusercontent.com/96970/123939720-ba5f5b80-d998-11eb-87da-b76875c6068e.png)
![image](https://user-images.githubusercontent.com/96970/123940022-0f9b6d00-d999-11eb-8119-c54be5de914b.png)
