### ISSUE TITLE
Release candidate 2.0.0 checklist

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2102]
- [x] Release blockers
    - [x] Missing frontend translation "Repeating Group" & various configuration options
    - [x] Check radio input "checked" alignment
    - [x] CSRF problem when logged in to admin + embedding a form
    - [x] SDK + backend CSRF tightening (update compatible versions docs!)
    - [x] Release SDK 1.2.1 and pin version in `.sdk-release`
- [x] Bump version
- [x] Update changelog
- [x] Tag release candidate
