### ISSUE TITLE
Restoring an old form version deletes the existing submission steps

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2135]
### Product versie / Product version

1.1.7

### Omschrijf het probleem / Describe the bug

Taiga Venray 37

If there are existing submissions for a form and the configuration of the form is changed by restoring an old version, then the submission steps are deleted. This is because there is a `on_delete=CASCADE` on the `form_step` field of the submission step.

### Stappen om te reproduceren / Steps to reproduce

- Create a form with a text field `textFieldA`
- Fill in and submit the form
- Update the form so that `textFieldA` becomes `textFieldB`
- Save the configuration
- Now in the history of the form, restore the old version of the configuration (`textFieldA` is back)
- Look at the submission => The submission steps are gone

### Verwacht gedrag / Expected behavior

The data of old submissions should not be deleted

## Tasks

- [x] Apply fix to stable/1.1.x
- [x] Apply fix to stable/2.0.x
- [x] Apply fix to master

**Comment by CharString** [comment]
Imho deletion of a submission isn't even the worst that can happen. As is, the `Submission` has a FK to a `Form`, where it should be a `FormVersion` with the export_blob representing the questions that I, as the submitter were presented... Deletion is the "good" case, far worse would be when the semantics of a question in a step has changed! The municipality could potentially make decisions on a representation of my answers in a completely different context. Simplest example being the boolean question `A` could be rephrased to be `¬A` rendering my answer to be the complete opposite.

This goes beyond the scope of a bug fix, but contains a  story or two: "As a citizen filling forms that have legal consequences, I'd like to have the pdf download signed with the site certificate." This would is the digital equivalent of my going into town hall and getting a [carbon copy](https://en.wikipedia.org/wiki/Carbon_copy) with a [stamp](https://en.wikipedia.org/wiki/Rubber_stamp) and signature of the civil servant or official for receipt.

From first inspection  of the test suites where `SubmissionFactory` is used, the simplest refactor that could possibly work, is have the `Submission` have a FK to `FormVersion` and make `Submission.form` a property that rehydrates a `Form` from the `FormVersion.export_blob`... But this has consequences for migrations of the underlying models too.

**Comment by sergei-maertens** [comment]
> Imho deletion of a submission isn't even the worst that can happen. As is, the `Submission` has a FK to a `Form`, where it should be a `FormVersion` with the export_blob representing the questions that I, as the submitter were presented... Deletion is the "good" case, far worse would be when the semantics of a question in a step has changed! The municipality could potentially make decisions on a representation of my answers in a completely different context. Simplest example being the boolean question `A` could be rephrased to be `¬A` rendering my answer to be the complete opposite.
> 
> This goes beyond the scope of a bug fix, but contains a story or two: "As a citizen filling forms that have legal consequences, I'd like to have the pdf download signed with the site certificate." This would is the digital equivalent of my going into town hall and getting a [carbon copy](https://en.wikipedia.org/wiki/Carbon_copy) with a [stamp](https://en.wikipedia.org/wiki/Rubber_stamp) and signature of the civil servant or official for receipt.
> 
> From first inspection of the test suites where `SubmissionFactory` is used, the simplest refactor that could possibly work, is have the `Submission` have a FK to `FormVersion` and make `Submission.form` a property that rehydrates a `Form` from the `FormVersion.export_blob`... But this has consequences for migrations of the underlying models too.

We are aware of this and for the time being this is an accepted risk. Relating a submission to form versions is a whole other Pandora's box, because the serialized form definitions/data/configuration is not necessarily forwards or backwards compatible with newer/older versions of Open Forms (because of instance upgrades).

**Comment by sergei-maertens** [comment]
So an *interesting* behaviour is that the actual data on 2.0.0+ is not gone because it's stored in variables and this bug mostly affects 1.x in this case.
