### ISSUE TITLE
Update the snippet shown in the admin

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2145]
### Thema / Theme

Form designer

### Omschrijving / Description

With the rising demand to use the snippet, we need to improve it. This ticket covers the basics, the rest is in #2146 for later.

The current snippet shows 2 lines:

```html
<div id="openforms-container"></div>
<script src="/static/sdk/1.2.1/open-forms-sdk.4941161bc754.js"></script>
<script nonce="pG+bmK5gWv6znSCY4Z8utA==">
    const formId = 'example';
    const baseUrl = 'https://example.com/api/v1/';
    const targetNode = document.getElementById('openforms\u002Dcontainer');
    const basePath = '/example/';
    const CSPNonce = 'pG+bmK5gWv6znSCY4Z8utA\u003D\u003D';
    
    const sentryEnv = 'maykin\u002Dtest';
    const form = new OpenForms.OpenForm(
        targetNode,
        { baseUrl, formId, basePath, CSPNonce, sentryEnv }
    );
    form.init();
</script>
```

and

```html
<link href="/static/sdk/1.2.1/open-forms-sdk.783475e7e294.css" rel="stylesheet" />
```

**Tasks**

* [ ] Replace `CSPNonce` and the `script nonce` value with a static `REPLACE-WITH-DYNAMIC-CSP-NONCE`
* [ ] Add the full URL to the script and css URLs
* [ ] Use the generic URLs from ticket #2141 
* [ ] Comment out `basePath` and set the value to a static `REPLACE-WITH-RELATIVE-WEBSITE-URL`
* [ ] Comment out and empty `sentryEnv`

**Comment by sergei-maertens** [comment]
-> just remove the snippet
