### ISSUE TITLE
Kaartmateriaal - Zoeken op adres

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2174]
Als burger wil ik binnen de kaart-interface mijn adres kunnen zoeken, zodat de kaartserver op basis van mijn zoekopdracht het adres en de juiste coordinaten toont en verwerkt.

Voorbeeld: PDOK locatieserver: [Introductie - PDOK](https://www.pdok.nl/introductie/-/article/pdok-locatieserver-1)

**Tasks**

* [x] Invoerveld toevoegen voor adres
* [x] Automatisch meer inzoomen als je dit doet.
* [x] Ook gemeente ophalen uit Locatieserver

Oorsprong: https://github.com/Dimpact-Samenwerking/Open-Formulieren/issues/41 RTM: 7.10 Story points: 5 Business value: 3

**Comment by StefSchots1993** [comment]
[PF-33](https://dimpact.atlassian.net/browse/PF-33) aan onze kant ook geupdate met verduidelijking van Haarlemmermeer.
Vraag: Worden coördinaten voortkomend uit zoekopdracht op adres of plaatsen van een pin op de kaart ook weggeschreven in de inzending / productaanvraag?

**Comment by hlmr-erik** [comment]
@bart-maykin Het tweede deel van de story zie ik nog niet terug, klopt dit? Het kan zijn dat ik via Docker nog niet de laatste versie heb binnengehaald. Dit gaat om het deel dat ik een punt aanklik, en dan het dichtstbijzijne adres terugzie in een (invul)veld


![Image](https://github.com/open-formulieren/open-forms/assets/111565013/249d3590-7df7-4a55-a87e-d51838bfaef4)

**Comment by sergei-maertens** [comment]
Klopt, @bart-maykin het gaat dus om dit aspect:

> Wanneer de functionaliteit werkt willen we ook dat het visa versa werkt, dus als ik op de kaart een locatie klik. Hij moet dan eerst het dichtstbijzijnde adres opzoeken adhv coördinaten en dat adres tonen in het invoerveld of ergens anders.

**Comment by hlmr-erik** [comment]
Wellicht rijkelijk laat, maar het gaat er dus om dat het adres als invoer van een veld meegenomen wordt met de inzending. Niet alle BE systemen die de data verwerken hebben namelijk de capaciteit om de coördinaten te plotten en zelf om te zetten in een adres.

**Comment by joeribekker** [comment]
> Wellicht rijkelijk laat, maar het gaat er dus om dat het adres zoals een (invoer)veld meegenomen wordt met de inzending. Niet alle BE systemen die de data verwerken hebben namelijk de capaciteit om de coördinaten te plotten en zelf om te zetten in een adres.

Ik beschouw dit als een andere user story. Dat betekent dat we dit ticket niet uitbreiden met deze functie.

**Comment by hlmr-erik** [comment]
@joeribekker ok, dan ga ik even overleggen wat de beste manier is om dit op te volgen. 
Nog om te checken of ik geen instelling gemist heb: 1. Klopt het dat de kaart niet meekomt naar de PDF, alleen de coördinaten? en 2. Klopt het dat de downloadknop voor de PDF op de bevestigingspagina niet uit te zetten is?

**Comment by sergei-maertens** [comment]
Frontend PR still to be done
