### ISSUE TITLE
Add django-modeltranslation to manage Django model fields translations

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2230]
Epic #2170 

**Tasks**

- [ ] Add django-modeltranslation dependency, with admin integration
- [ ] Make `forms.Form` model fields translatable:
    - `name`
    - `submission_confirmation_template`
    - `begin_text`
    - `previous_text`
    - `change_text`
    - `confirm_text`
    - `explanation_template`
- [ ] Make `forms.FormStep` fields translatable:
    - `previous_text`
    - `save_text`
    - `next_text`
- [ ] Make `forms.FormDefinition` fields translatable:
    - `name`
- [ ] Make `emails.ConfirmationEmailTemplate` fields translatable:
    - `subject`
    - `content`
- [ ] Make `config.GlobalConfiguration` fields translatable:
    - `submission_confirmation_template`
    - `confirmation_email_subject`
    - `confirmation_email_content`
    - `save_form_email_subject`
    - `save_form_email_content`
    - `form_previous_text`
    - `form_change_text`
    - `form_confirm_text`
    - `form_begin_text`
    - `form_step_previous_text`
    - `form_step_save_text`
    - `form_step_next_text`
    - `privacy_policy_label`
