### ISSUE TITLE
Ensure that API endpoints return translated content

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2231]
Epic #2170 - depends on #2230 

**Tasks**

- [ ] Check if we can make test factories language aware - would be cool if we can do `FormFactory.create(language="nl", name="Testformulier")` leading to the correct underlying DB field/column being populated. This may default to `settings.LANGUAGE_CODE`
- [x] Add integration test for languages NL/EN to verify that the endpoints return the correct language.
- [x] Add test variants for language cookie and `HTTP_LANGUAGE` request headers
