### ISSUE TITLE
Add toggle to enable/disable translations per form

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2232]
Epic #2170

---

Migration wise best to implement this after #2230 

---

**Tasks**

- [x] Add a new field to the `Form` model: `i18n_enabled` - default to `False` for backwards compatibility
- [x] Expose the field in the public API endpoint (the SDK needs to be aware of this configuration)
- [x] Ensure that when i18n is disabled, the language is _forced_ to `settings.LANGUAGE_CODE` (i.e. `HTTP_LANGUAGE` and/or language cookie are ignored)
