### ISSUE TITLE
Een gebruiker kan een formulier tussentijds kunnen opslaan en op een later moment afronden (deze eis valt ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#227]
...buiten het MVP).

Eis: Sturing Formulier 1.
Zie ook NvI: 74, 153

**Tasks**

* [x] When clicking the "Tussentijds opslaan" button, present the user with a popup/modal to explain this feature, provide an emailaddress to sent the "continue" link to, button to confirm & logout or cancel this popup.
* [x] The user should be logged out after clicking confirm & logout
* [x] The user should recieve an email with a magic-token link to continue the form
* [x] When the link is clicked, the form & session should be restored.
* [x] The email should contain the information until the form can be continued (submissions are deleted after X days due to cleanup policies)

**Comment by sergei-maertens** [comment]
Back to TODO - depends on #709
