### ISSUE TITLE
Import/export & version creation/restoration needs to bring translations along

### ISSUE THREAD

**Issue by stevenbal** [open-formulieren/open-forms#2287]
Epic #2170 

For now we keep the existing import/export machinery, rework/refactor is scheduled for #1300.

The API endpoints now (mostly) support translations for the Django fields via #2317, and as the export/import uses the API serializers, we should be able to include translations.

**Tasks**

- [ ] Ensure translations of forms are exported along with the forms themselves
- [ ] Ensure that translation-enabled exports can be imported and load the translations correctly
- [ ] For exports made BEFORE 2.1.0 - see if we can take the regular fields and put them in the `FOO_nl` fields if translations are missing - this is a best effort to support older export formats lacking translation information. Be pragmatic about this!
