### ISSUE TITLE
Normalize (variable) data types

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2324]
See also #2251
See also #2305 (using local type information instead of requiring formio definitions would be very useful)

In short - we need to ensure that all (input) data has the correct type for processing in python and when calculations are done with json-logic, we need to serialize back to json-types and all data needs to be properly normalized.

We have essentially the following flow of information:

```

                                             +------------------+
+------------+      +----------------+       | Logic evaluation |____\ - output data (JSON)
| Input data |____\ | backend        |____\  | (JSON)           |    / - updated variable values (python/JSON)
| (JSON)     |    / | (python types) |    /  +------------------+
+------------+      +----------------+        ^
                                              |
                    +----------------+        |
                    | logic rules    |________+
                    | (JSON)         |
                    +----------------+

```

The 'problem' with JSON is that it only has a number of primitives that are used for richer Python types:

* string <-> date
* string <-> datetime
* string <-> duration
* string <-> time
* number <-> int
* number <-> float
* number <-> decimal
* ...

This is further complicated with the formio component types and the notion of single/multiple values (array vs. primitive).

## Using the python datatypes

Simply just using JSON types (complex & primitives) is not sufficient because we cannot do smart operations on them. We *must* support (non-exhaustive list) the following operations:

* formatting for display using Django's template language filters (e.g. `|date`, `|time`, `|floatformat` )
* calculations, e.g. `timestamp + timedelta`
* private API: introspecting/invoking methods - if we have strategy objects encapsulating data (dataclasses!) we want to use those to the full extent
* deep data extraction/assigment operations (e.g. using `glom` or `jq` to read/write certain data)
* submission data exports (tablib) also benefits from python types for serialization

## Identified boundaries

We can identify "our own code" as the system boundary. This implies:

* data enters this boundary (via the API endpoints) as JSON, once the boundary is being crossed we transform this into the relevant python types. For input variables, we can use the `FormVariable` type information (see `SubmissionValueVariable.to_python`)
* data enters this boundary (from the database adapter) as JSON (JSON logic expresions/rules). We cannot infer a more detailed type here - a string may be a date, datetime, date or simply a literal text.
* data exits the boundary once we pass it to third party libraries (json-logic)
* data exits the boundary once we serialize back for API responses
* data exits the boundary once we store variable values in the database (as JSON)

note: 'as JSON' implies the result of `json.loads(...)` here, so we have python dicts/lists/strings/ints/floats/NoneType.

## handling JSON logic

The JSON logic library essentially operates on JSON primitives (or complex objects) and we should deal with that. This is particularly challening when comparing datetimes (or dates and datetimes) for example:

`2022-11-08T14:12:00+01:00` is equal to `2022-11-08T13:12:00+00:00` and `2022-11-08T13:12:00Z` - but simple string operations will not give the same result.

We need to normalize JSON logic expressions with the available type information at save time so that runtime is as simple as possible:

* [ ] Investigate normalizing date/datetime literals to be in the same timezone (`settings.TIMEZONE`)
* [ ] Investigate date/datetime + timedelta operations

A conclusion may be that we need to pass python-objects (datetimes) down to json logic rather than just serialized versions.

## Tasks taken from [refinement](https://github.com/open-formulieren/open-forms/issues/2324#issuecomment-1470333866)

* [x] #2959
* [x] Prototype the conversion to Python type  (step 2)
* [ ] Prototype the preprocessing (step 3)
* [ ] Clean up (track down and burn them) existing workarounds for dealing with datatypes
* [ ] Migrate JSON-logic rules

**Comment by SilviaAmAm** [comment]
Additional thoughts: 
At the moment we have:
- JSON data coming into component / user defined variables
- Static variables are in python type (this I have changed in my PR for #2251)

Before my PR, we were using python data for the json logic. If the PR is merged we would have:
- JSON data for the logic
- Python data for injection into the dynamic configuration
- String representations for the rendering

**Comment by SilviaAmAm** [comment]
Additional example: dealing with currency / number component
- For the calculations we need to have the currency as a float
- For displaying in the form we need to have the value formatted with the right number of decimals as configured in the component
- For injecting into the configuration (content component, labels, help texts) we need to have  the currency symbol and the decimals `€ 123,00`.

**Comment by sergei-maertens** [comment]
blocked until we get the go-ahead for this

**Comment by SilviaAmAm** [comment]
Another issue related to types: https://github.com/open-formulieren/open-forms/issues/2707

**Comment by joeribekker** [comment]
The work on this cannot block releasing intermediate versions. So, working on this needs to be done outside of master OR as feature flag.

**Comment by sergei-maertens** [comment]
Chris mentioned that we can essentially do some type inference and "rewrite"/compile/transpile JSON logic expressions into equivalents that can be evaluated on both backend and frontend.

E.g. a string datetime + relative delta -> convert to unix timestamp (number) + delta (number) & the result can then be compared in terms of primitives.

**Comment by joeribekker** [comment]
data (1) -> convert (2) -> preproces (3) -> jsonlogic (4) -> convert (5) -> result (6)

1. JSON
2. Convert JSON to Python data, using datatype metadata
3. Convert Python to JSON suitable for JsonLogic
4. Execute JSON-logic with logic rules
5. Convert JSON result from JSON-logic to Python data, using datatype metadata
6. Use Python data in templates, component labels, API serializers

**Comment by joeribekker** [comment]
Refinement: We should create concrete things todo (=issues) with this ticket as the main epic.

**Comment by viktorvanwijk** [comment]
## Current situation
With the work done in #5139, `evaluate_form_logic` fully reasons in the Python type domain:
1. Step data is saved to the state
2. All data in the state is converted the Python type domain
3. JSON logic is performed with Python types (this is possible because of custom json-logic package that supports this: maykin-json-logic-py)
4. JSON logic results are converted back to the Python type domain and all mutations are tracked
5. Only mutations are saved to the state, so it currently contains a mix of JSON primitives are Python types

## Things that still need attention
* Need to convert all the data to the Python types, which means `.get_data()` and `.to_python()` of `SubmissionValueVariablesState` need to be combined. Note here that `to_python` includes also static variables, and that there is a sensitive-data cleaner inside `get_data`. Not sure if the latter is still relevant though

* Conditional logic is currently not converted to the Python type domain, so any logic that involves date, time, or datetime fields will  fail (see test `test_component_visible_with_date`)

* User-defined variables:
  * It seems like we currently only check the initial value upon saving the variable (with `FormVariable.check_data_type_and_initial_value`). For example, when trying the form when setting a string to a variable of type object, no error is shown, but after reloading is completed the value will still be an empty object. When trying to change an array to a string, the variables table actually crashes completely: 

    ![Image](https://github.com/user-attachments/assets/c8f65efb-0dc5-42e8-ad9c-e31520e7a748)
  
  * There is no way to guarantee the values inside an array, though. Could be an array of strings, int, floats, or a combination of these
  * The time data type has a textbox as input field, whereas date and datetime objects have a date and datetime picker input field, respectively:
  
    ![Image](https://github.com/user-attachments/assets/bab3d451-1832-4d10-af86-17e11eb0999a)
    ![Image](https://github.com/user-attachments/assets/0da775d2-a4f5-4788-82cb-ba0999275c69)

  * Seems like we can do a little bit more by raising errors if the type of the value does not match the specified type of the variable, instead of falling back to an empty value silently

* Depending on if we still want to drop support for Python types inside JSON logic, see [comment](https://github.com/open-formulieren/open-forms/issues/2324#issuecomment-1470333866), we need to convert the Python types back to strings before JSON-logic evaluation.

* Issues linked in this ticket:
  * #2707: the description here no longer accurately reflects what happens when the variable is set in the action. Currently, the value is converted to the Python type domain in `iter_evaluate_rules`, using the data type information of the variable. If this conversion fails because of an invalid value, it falls back to `None`. The form no longer crashes
  * #4883: not 100% sure, but this might be solved when we start using `.to_python` instead of `.get_data` everywhere
  * #2941: not exactly sure if and/or how this can be solved. Seems like the presented example is more about invalid JSON logic?

**Comment by joeribekker** [comment]
Refinement: Once #5467 PR is closed, this ticket will be closed and remaining work exists in other issues. These other issues are not blocking for "the performance stuff".
