### ISSUE TITLE
Een gebruiker kan via condities in een formulier meerdere of diverse betaalmogelijkheden beschikbaar hebben. Voorbeeld: ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#235]
...Bij resultaat A betaalt een bezoeker 50 euro, bij resultaat B 100 euro (deze eis valt buiten het MVP).

Eis: Sturing Formulier 9.
Zie ook NvI: 76, 158

**Tasks**

* [x] Add form logic action to set (and override) the price (if choice A then price=X; if choice B then price=Y)
* [x] Save the resulting price on the form
* [x] Make sure the overriden price is used when submitting the form (in summary and in payment)

**Comment by sergei-maertens** [comment]
Discussed yesterday with Joeri.

The simple implementation would be:

1. Use static pricing (from connected product) or dynamic pricing (see 2.)
2. Define conditions just like in form logic "when component X has value Y" -> then set price A

Multiple rules are possible that change the price and the connected product price is no longer used.

**Comment by joeribekker** [comment]
We will go for option 2, which will also imply to remove Products entirely, and set arbitrary prices on the form itself (instead of products). Ticket updated with specs.

**Comment by joeribekker** [comment]
Issue #187 conflicts with my earlier comment...

I think both issues conflict a bit anyway: Manage prices centrally (#187) VS Allow per form price adjustments based on logic (this issue).
