### ISSUE TITLE
Een gebruiker kan de inhoud van een bevestigingsmail laten afhangen van de keuzes die de gebruiker maakt in het ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#239]
...formulier. Voorbeeld: vergunning A is aangevraagd, dus tekst X komt in beeld. Vergunning B is aangevraagd dus tekst Y komt in beeld of een afspraak is gemaakt voor paspoort, de meeneeminformatie voor paspoort wordt opgenomen. Als een afspraak is gemaakt voor een identiteitskaart komt de meeneeminformatie voor identiteitskaarten in beeld.

Eis: Verzending 4.

**Actie nodig van gemeenten**

- [ ] Geldt dit alleen voor afspraken? We kunnen niet aan elk veld maar de mogelijkheid hangen om een bepaalde tekst te tonen.

**Tasks**

- [x] Document how mail templating works (limit scope to if-statements and variables).
- [x] Document an example on how to create an if statement in a mail, that looks at a form variable to show a certain text or not.
