### ISSUE TITLE
Een gebruiker krijgt na het indienen van het formulier een melding te zien dat de aanvraag is verzonden.

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#243]
Eis: Verzending 8.

**Verduidelijking**

See tasks.

**Tasks**

- [x] Add global configuration to configure the content to show on the confirmation page (simple but richtext, see email editor for example).
- [x] Add form specific override to configure the content to show on the confirmation page. Add a boolean field should be added to indicate to use the override (or not).
- [x] Both contents should have access to the full submission context (all submitted fields) so you can add content like: "Thanks {{ first_name }}! We'll get right on it!".

**Vragen voor gemeenten**

In de basis voldoen we aan deze user story zodra er "bedankt" op het scherm komt na het insturen van het formulier, maar we will er toch iets meer mee doen:

* [x] Wat voor melding moet er op deze pagina komen?
* [x] Is deze melding in te stellen? Zo ja, op algemeen niveau (voor alle formulieren) of per formulier?
* [x] Moet deze melding nog "dynamische" informatie bevatten? Denk aan het zaaknummer (wat niet in alle gevallen beschikbaar is, of niet direct beschikbaar is).

Het is makkelijk om overal ja op te zeggen, maar ik hoop dat jullie vooral kijken naar wat nodig is. 😇
