### ISSUE TITLE
Een gebruiker weet ik dat de auditing en logging goed georganiseerd is. De inschrijver beschrijft de functionaliteit ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#247]
...van de oplossing met betrekking tot auditing en logging. Hierbij zijn de volgende zaken belangrijk (deze eis valt buiten het MVP): 

a. De verschillende handelingen en pogingen daartoe waarvan logging plaatsvindt. 
b.De verschillende elementen waarop dergelijke handelingen worden gelogd. 
c. Wat er precies wordt vastgelegd. - De wijze waarop gegevensuitwisseling via koppelvlakken wordt gelogd en geaudit. 
d. Hoe lang de logs bewaard blijven, inclusief de flexibiliteit dienaangaande. 
e. In welke mate en op welke wijze dit middels configuratie door de contractant is ingericht in de oplossing. 
f. In welke mate en op welke wijze functioneel beheerders van gemeenten volledig zelfstandig, zonder dat daarvoor geavanceerde programmeer-kennis nodig is (zero coding), kunnen beheren.

**Technische en functionele logging:**

g. Logbestanden worden zodanig beschermd dat deze niet aangepast of gemanipuleerd kunnen worden.
h. De oplossing maakt het mogelijk dat het raadplegen van logbestanden is voorbehouden aan geautoriseerde gebruikers. Hierbij is de toegang beperkt tot leesrechten.
i. In een technische logregel worden in geen geval gevoelige gegevens opgenomen. Dit betreft onder meer gegevens waarmee de beveiliging doorbroken kan worden (zoals wachtwoorden, inbelnummers, enz.)

Eis: Techniek 3.
Zie ook NvI: 53, 112, 113

**Tasks**

Ik wil dit ticket aangrijpen om [timeline logger](https://github.com/maykinmedia/django-timeline-logger) te introduceren.

* [x] Log all submission (API) actions
    * [x] submission
    * [x] registration
    * [x] payment
    * [x] prefill
    * [x] PDF
    * [x] confirmation email
    * [x] appointment: moved to #703
* [x] Gebruik per module een template (zie: https://django-timeline-logger.readthedocs.io/en/latest/usage.html#custom-messages-using-templates-and-context )
* [x] Alle log items dienen gerelateerd te zijn aan een submission (indien van toepassing) zodat je bij een submission een volledige log kan opvragen.
* [x] Add overall logging views to admin/admin-index
* [x] Add logging inline to submission model in admin, make sure all these models are read only.
* [x] Check logging model-admin, make sure it is read only.

**Example**

```
[2021-09-06 10:00:00] (Submission ae6f32): Anonymous user starts new submission for form "Aanvraag paspoort" (ID: 3).
[2021-09-06 10:00:10] (Submission ae6f32): Anonymous user fills step "Persoonlijke gegevens" (ID: 52) for form "Aanvraag paspoort" (ID: 3).
[2021-09-06 10:00:16] (Submission ae6f32): Prefill plugin "MyBAG-API" (BAG API) reported: Failed to retrieve information.  # Request/response in details
[2021-09-06 10:00:19] (Submission ae6f32): Prefill plugin "MyBAG-API" (BAG API) reported: Succesfully retrieved information.  # Request/response in details
[2021-09-06 10:00:31] (Submission ae6f32): Anonymous user submitted form succesfully.
[2021-09-06 10:00:31] (Submission ae6f32): PDF-generation task scheduled.
[2021-09-06 10:00:31] (Submission ae6f32): PDF generated succesfully.
[2021-09-06 10:00:31] (Submission ae6f32): Registration task scheduled.
[2021-09-06 10:00:33] (Submission ae6f32): Registration plugin "Open Zaak test" (ZGW APIs) reported: Registration succeeded.   # Request/response in details
[2021-09-06 10:00:34] (Submission ae6f32): Confirmation email task scheduled.
[2021-09-06 10:00:34] (Submission ae6f32): Confirmation email sent.
```

Typically, an event reports 1 or 2 things: start (for async tasks) and result (just results for synchronous tasks are probably sufficient to keep the logs clean)
