### ISSUE TITLE
Change appointments flow

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2471]
Based on #2265 there's a number of things that needs to be done. This ticket describes the technical implications, still in a higher level.

In summary:

1. We will remove the appointment-field mapping functions from the designer entirely
2. A form can be marked as an "appointment-form"
3. The frontend will have a dedicated page/flow for appointments (not bound to form-steps)

### Tasks

@sergei-maertens wants to introduce Formik.

* [x] Transform the JCC and Qmatic "clients" into proper plugins - PR #2515 
* ~~Remove AppointmentsConfig model where the client is selected~~ **Upd. decided to keep this config on application level**
* ~~Add the selection of the appointmentsplugin to the Form designer tab: Afspraken (thus, it is saved per form). If a selection is made, appointment mode is activated.~~ **Upd. decided to keep this config on application level**
* ~~Add the appointment-mode to the API so the frontend can render te proper views~~ **Moved to the next iteration**
* ~~Create a frontend appointment-flow, according to the mockup below~~ **Moved to the next iteration**
* [x] Allow for multiple products to be selected (this is already supported in the client)
* [ ] Allow for multiple people to make the appointment (not supported yet in the client I think).
* [ ] Allow a query-param, to pre-select a certain product, ie: `/afspraak-maken?product=abc` will select product `abc` in the pulldown.

**Optional**

* [x] If there is only 1 location available, don't ask the user for the location but just "select" it
* [x] #3193

### Mockup

Please ignore menu's and button layout, and layout in general. Use as much of existing layout as possible. See storybook.

**Step 1**

<img src="https://user-images.githubusercontent.com/96970/207066558-bd5b09bc-6805-49db-8ffa-fc6d91c47d10.png"  width="400">

**Step 2**

<img src="https://user-images.githubusercontent.com/96970/207069233-b7c1a279-7401-4281-80a0-84d90c9285fb.png"  width="400">

Alternative:

![image](https://user-images.githubusercontent.com/96970/207078439-08b43b81-43da-4a35-9d33-d95c38601ce4.png)

**Step 3**

<img src="https://user-images.githubusercontent.com/96970/207069009-f834ca29-8b24-4c3f-b253-bcc6ce81902a.png"  width="300">

**Step 4**

Any other form steps and the regular summary/confirmation page.

**Comment by joeribekker** [comment]
Moved next iteration to #2543
