### ISSUE TITLE
Add Site-ID and folder support for Microsoft Graph registration plugin

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2511]
Currently, the Microsoft Graph registration plugin does not offer any options:

![image](https://user-images.githubusercontent.com/96970/208897594-9b297f4a-f527-47ea-8e0d-56cb53748f1e.png)

However, we should be able to provide a path, like: `/sites/my-site/open-forms/` and all files should be stored there, in a folder. So, `/sites/my-site/open-forms/OF-12345/`, `/sites/my-site/open-forms/OF-67890/`, etc. (name of the folder should be simply the submission registration identifier that we already have at that point).

Background: https://learn.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-1.0&tabs=http
Background: https://learn.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-1.0#sharepoint-api-root-resources

**Tasks**

* [x] Add path configuration field to form configuration (see other registration plugins for examples - and image below)
* [ ] Make sure the configured path is respected when sending Drive-items to Microsoft Graph API
* [x] Add tests for this using mocking Graph API responses
* [ ] Perform live test on Sharepoint test environment
* [x] Bonuspoints: Allow date-element placeholders in the configured path: `/sites/my-site/open-forms/{year}-{month}-{day}/` This folder then also needs to be created if it doesn't exist.

![image](https://user-images.githubusercontent.com/96970/208899586-912c6f54-eabf-415d-a5f6-bb3aa65f8b87.png)

**Comment by SilviaAmAm** [comment]
Microsoft Graph does a "get or create" when uploading a file for the folders in the path of the file
