### ISSUE TITLE
Als beheerder wil ik een formulieren component die kan werken met NLX. Dat betekent onder andere dat authenticatie- ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#255]
...en audit-voorzieningen kunnen worden gebruikt (deze eis valt buiten het MVP).

Eis: Beveiliging En Privacy 1.
Zie ook NvI: 169

**Tasks**

* [x] Setup an NLX outway for Maykin test OF.
* [x] Demo that we can configure and use NLX between Open Forms and Open Zaak.
* [x] Update zgw-consumers NLX integration following the recent breaking change

PS. I requested a view on transaction logs @ NLX team: https://gitlab.com/commonground/nlx/nlx/-/issues/1378

**Comment by sergei-maertens** [comment]
NLX stack is now deployed on our test environment:

* Management UI
* Inway
* Outway

In the inway, we expose two services from test.openzaak.nl since the other example services on the demo network do not have much value and bullet two requires demo-ing that we can consumer services.

The outway is configured in our maykin test instance and access requests have been made (+ fulfilled) to both Open Zaak services.

**Comment by joeribekker** [comment]
Wilde toch in dit gesloten ticket nog even noemen dat het NLX dashboard op ons verzoek nu een transaction log heeft:

![image](https://user-images.githubusercontent.com/96970/147068714-79b96e3c-5157-4391-ae7c-f491e27acf7d.png)
