### ISSUE TITLE
Als beheerder wil ik dat de beveiliging van de webapplicaties van de oplossing voldoet aan de NCSC ICT-beveiligingsrichtlijnen ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#257]
...voor webapplicaties.

Eis: Beveiliging En Privacy 3.

**Invulling**

Deze staan hier beschreven: https://www.ncsc.nl/documenten/publicaties/2019/mei/01/ict-beveiligingsrichtlijnen-voor-webapplicaties

Een deel hiervan wordt getackled door ISO 2700x:

![image](https://user-images.githubusercontent.com/96970/133044961-9c70a8dc-e86c-4a66-a7b9-865c10a16437.png)

Maatregelen genoemd in bovenstaande documenten worden opgevolgd. Ten behoeve hiervan zijn nog enkele taken nodig:

**Tasks**

* [x] Vaste groepen aanmaken voor gebruikers: Redacteurs (mogen formulieren maken), Functioneel beheerders (mogen configuratie aanpassen en accounts aanmaken), Beheerders (mogen alles, geen superuser), Behandelaars (mogen inzendingen inzien) (Beveiligingsrichtlijn B.02)
* [x] Toon groepen en superuser flags in User list view zodat de autorisatie matrix helder is.
* [x] Nginx headers zoveel mogelijk beperken (vraag Alex).
* [x] Stel voor alle cookies de flags ‘secure’ en ‘HttpOnly’ in (zie Django docs). Getackled [hier](https://github.com/open-formulieren/open-forms/blob/master/src/openforms/conf/base.py#L425) en [hier](https://github.com/open-formulieren/open-forms/blob/master/src/openforms/conf/base.py#L418).

**Comment by joeribekker** [comment]
Deze staan hier beschreven: https://www.ncsc.nl/documenten/publicaties/2019/mei/01/ict-beveiligingsrichtlijnen-voor-webapplicaties

Een deel hiervan wordt getackled door ISO 2700x:

![image](https://user-images.githubusercontent.com/96970/133044961-9c70a8dc-e86c-4a66-a7b9-865c10a16437.png)

Maatregelen genoemd in bovenstaande documenten worden opgevolgd. Ten behoeve hiervan zijn nog enkele taken nodig:

* [ ] Vaste groepen aanmaken voor gebruikers: Redacteurs (mogen formulieren maken), Functioneel beheerders (mogen configuratie aanpassen en accounts aanmaken), Beheerders (mogen alles, geen superuser), Behandelaars (mogen inzendingen inzien) (Beveiligingsrichtlijn B.02)
* [ ] Toon groepen en superuser flags in User list view zodat de autorisatie matrix helder is.
* [ ] Nginx headers zoveel mogelijk beperken (vraag Alex).
* [ ] Stel voor alle cookies de flags ‘secure’ en ‘HttpOnly’ in.
* [ ] Verstuur bij alle http-responses de http-headers ‘Content-Security-Policy: frame-ancestors’ en (tijdelijk) ‘X-Frame-Options’.
