### ISSUE TITLE
Using a '-sign in email subjects goes wrong

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2587]
![image](https://user-images.githubusercontent.com/96970/213407579-04c68361-8578-45df-bba1-41ccf53796fc.png)

**Tasks**

* Create test that shows this happens in:
  * [ ] Email subjects used in emails to email registration backend
  * [ ] Email subjects used in confirmation-emails to submitters
* [ ] Don't escape/encode HTML-entities in email subjects
