### ISSUE TITLE
De gebruiker werkt veilig met formulieren. De toepassing voldoet aan de Algemene verordening gegevensbescherming ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#260]
...(AVG). Dit betekent dat:

a. De leverancier heeft bij de softwareontwikkeling privacy by design ingericht. Daarnaast heeft de leverancier privacy by default ingericht binnen de processen en systemen.
b. Er wordt gelogd wie waarom en wanneer welke persoonsgegevens verwerkt. Deze logging wordt eenvoudig ontsloten voor zowel de privacy-functionarissen van de gemeenten, als ook de inwoners wiens gegevens het betreft.
c. Wie heeft wanneer, en waarom welke gegevens 'verwerkt' 
 1. Voor welke handelingen en pogingen daartoe vindt logging plaats
 2. Voor welke elementen worden dergelijke handelingen gelogd.
 3. Wat er precies wordt vastgelegd.
 4. De wijze waarop gegevensuitwisseling via koppelvlakken wordt gelogd en geaudit.

d. Hoe lang de logs bewaard blijven, incl. de flexibiliteit mbt bewaartermijnen en de verschillende logs
e. In een logregel worden geen geval gevoelige gegevens opgenomen. Dit betreft niet alleen
persoonsgegevens maar ook gegevens waarmee de beveiliging doorbroken kan worden (zoals
wachtwoorden, inbelnummers, enz.)
f. Logbestanden worden zodanig beschermd dat deze niet aangepast of gemanipuleerd kunnen
worden.

Eis: Beveiliging En Privacy 6.
Zie ook NvI: 58, 113

**Tasks**

See also #247 to introduce timeline logger.
Specifically add logging statements for the Prefill plugins StUF-BG and HaalCentraal to...

* [x] Log the retrieval of personal data and which fields specifically and which attribute is used from the API/SOAP mapping. (see example below)
* [x] Log the viewing of admin submission details
* [x] Log the viewing of api submission details
* [x] Log the admin (and api?) export of submissions
* [x] These logs need to be tagged or labelled to identify AVG-related logs
* [x] These logs need a special view in the admin to see them (filtered on above label)

**Example: Prefill logging**

```
[2021-09-06 10:00:18] (Submission ae6f32): Prefill plugin "MyBG-service" (StUF-BG) retrieved personal data to prefill fields: Firstname (persoon.voornamen), Lastname (persoon.achternaam), Birthdate (persoon.geboortedatum).
```

**Example: User logging**

```
[2021-09-06 10:00:18] User "John Doe" viewed submission ae6f32 for form "Request passport".
```
