### ISSUE TITLE
Add support: Haal Centraal BRP v2.0

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2606]
### Thema / Theme

Plugins

### Omschrijving / Description
Internal: Utr 41, Enschede 9

Currently, version 1.3.1 is available in OF but everyone is migrating to v2.0 which will also be the national standaard (and I'm super happy that they didn't call it 1.0.0 again because it moved to a different department on paper!).

More info on HC BRP 2.0: https://brp-api.github.io/Haal-Centraal-BRP-bevragen/v2/getting-started

**Tasks**

* [x] In `haalcentraalconfig` rename existing label (Haal Centraal API) to "BRP Bevragen Personen service"
* [x] In `haalcentraalconfig` add a version dropdown: `BRP Bevragen Personen version`: 1.3 and 2.0
* [x] Make a data migration and make sure the default is set to 1.3 (currently supported version)
* [x] Change the existing plugin to support 2.0 behaviour (mostly about doing a POST instead of a GET)
* [x] Change the existing plugin to switch to 1.3 and 2.0 based on the `haalcentraalconfig`.
* [ ] Check if there any attribute changes in the 2.0 API compared to 1.3. There is a script or management command (created by @Bartvaderkin ) to generate the mapping from API attributes to choices.
* [x] If there are any changes, we need different mappings for both API versions (please keep a base mapping and deviate only where needed)
* [x] Restructure tests to differentiate between 1.3 and 2.0 mocks/tests
* [x] Add specific 2.0 tests

**Comment by StefSchots1993** [comment]
@LaurensBurger @joeribekker - Vanuit Rotterdam/Enschede het signaal dat we de ondersteuning van de nieuwe HC 2.0 versie in OF nodig hebben. 

1.  Kunnen jullie mij meenemen in een schatting van hoeveel werk het is dit te realiseren?
2.  afhankelijk van de benodigde effort, is dit wellicht in de huidige door Dimpact uitgevraagde sprint te passen?  2e sprintronde?

**Comment by RobertDorenbuschEns** [comment]
Versie 2.0 is nodig om de HC-BRP koppeling met RVIG te leggen. Oudere (huidige) versies worden niet ondersteund.

**Comment by joeribekker** [comment]
Ha @StefSchots1993, je weet hoe het werkt. Passen is niet het goede woord maar heeft het meer prio dan andere issues? Ik zal deze wel opnemen in ieder geval, met prio hoog en zal dan kijken of er niks afvalt.
