### ISSUE TITLE
De gebruiker kan een QR-code kunnen ontvangen die hij of zij mee kan nemen naar het gemeentehuis ter verdere afhandeling ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#262]
...van de afspraak. Deze optie vergt afstemming tussen de toepassing en het afsprakensysteem.

Eis: Afspraken 2.
Zie ook NvI: 59, 91

**Tasks**

* [x] Add appointment details function to API + Allow for arbitrary key/value pairs to include non-standaard information.
* [x] Include QR-code to the appointment details (it's JCC specific) as key/value pair
* [x] Include appointment details (see `get_appointment_details_html`) in the confirmation e-mail from the form submission if the form is an appointment form.
