### ISSUE TITLE
De gebruiker kan een afspraak annuleren of wijzigen via een url in een bevestigings e-mail.

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#263]
Eis: Afspraken 3.
Zie ook NvI: 60, 92

**Tasks**

* [x] Add API endpoint to cancel appointment.
* [ ] ~Add API endpoint to change the appointment.~
* [x] The API endpoints should take an appointment ID and an emailaddress as validation. The emailaddress should match the mail address where the confirmation mail is sent.
* [x] Add page (view/template/js/css-whatever) to cancel the appointment (see design below) + confirmation page (Afspraak succesvol geannuleerd).
* [ ] To change an appointment, we can use the link that was used to create the appointment in the first place. So, point the user to the "appointment form", keep track that it was an existing appointment, create the appointment afterwards and cancel the old one.
* [ ] Improvement over the previous bullet: Allow the pre-selection of a product using a query param: `/form/my-form?product=XYZ` and use this in the change appointment link (see below).
* [x] Add links to these pages in the confirmation email: 
  **Afspraak wijzigen of annuleren**
  o [Ik wil mijn afspraak annuleren]()
  o [Ik wil mijn afspraak wijzigen]()

**Design / mock**

![image](https://user-images.githubusercontent.com/96970/131111899-21670f3a-6266-49ba-8d2a-41a54fc9953b.png)
