### ISSUE TITLE
Prepare 2.1.0 release candidate

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2801]
The current state of `latest` seems pretty good, so we'll go straight from alpha to release candidate.

**Tasks**

- [x] Resolve release blockers
    - [x] #2805
    - [x] #2769
    - [x] #2798
- [x] Generate changelog
- [x] Release and pin to SDK version 1.3.0 (https://github.com/open-formulieren/open-forms-sdk/pull/373)
- [x] Check translations
    - [x] Backend
    - [x] Frontend
    - [x] Formio
- [x] Update API version & OAS
- [x] Update README with new API version links & release dates
- [x] Bump version number
