### ISSUE TITLE
Productaanvraag - Integratie Open Formulieren met de eSuite (Productaanvraag)

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2852]
### Thema / Theme

API

### Omschrijving / Description

**Specificatie en taken**

[Zie comments.](https://github.com/open-formulieren/open-forms/issues/2852#issuecomment-1571534979)

**Oorspronkelijke ticket**

Als Dimpact gemeente wil ik Open Formulieren kunnen integreren met de eSuite van ATOS zodat ik op langer termijn het eSuite formulieren component kan uitfaseren door het te vervangen door Open Formulieren omdat we de transitie maken van de eSuite naar het open source "PodiumD" van dimpact.

Om Open Formulieren met de eSuite te kunnen integreren willen we gebruik maken van "Object type" Productaanvraag voor een eenduidige gegevensuitwisseling. In een refinementsessie met Dimpact/ATOS (eSuite)/Maykin(Open formulieren)/ en Rotterdam is een aanpassing van de "Productaanvraag" gerefined waarbij het JSON schema is aangevuld.

Maykin heeft een voorstel gestuurd welke ATOS heeft bekeken/aangevuld en ter review heeft teruggestuurd naar Maykin.
Joeri B weet hiervan.

https://github.com/joeridiederen/objecttypes/blob/patch-1/community-concepts/productaanvraag/productaanvraag-dimpact

### Added value / Toegevoegde waarde

Voordeel van het gebruik van deze "productaanvraag" is een gemakkelijkere integratie tussen OF en eSuite. 

### Aanvullende opmerkingen / Additional context

Eigenlijk is dit de "epic" waar de volgende userstories onderdeel van uitmaken.
(Wordt verder aangevuld). 

**Tasks**

* [x] #2853
* [x] #2854
* [ ] #2855
* [ ] #2856
* [ ] #2857
* [x] #2858

**Comment by StefSchots1993** [comment]
https://dimpact.atlassian.net/browse/PF-43

**Comment by SilviaAmAm** [comment]
# Technical spec

## The problem

The form designers want to be able to configure the sturcture of the object that will be created in the Objects API when using the Objects API registration backend.
The JSON that is sent to the Objects API is:

```json
{
    "type": "https://objecttype.nl/api/v2/objecttype/123",
    "record": {
        "typeVersion": 1,
        "data": {...},
        "startAt": "01-01-2023",
    },
}

```
We want to make the data inside the key "data" customisable.

This custom template will work roughly as follows:
```python
from django.template import engines
import json

template = """
{
    "data": {% json_summary %},
    "bsn": "{{ auth_bsn }}"
}
"""

django_engine = engines["django"]
template = django_engine.from_string(template)
body = template.render({
    "auth_bsn": "123456789",
    "data": {"key1": "value1", "key2": "value2"}
})

print(json.loads(body))
# prints: {'data': {'key1': 'value1', 'key2': 'value2'}, 'bsn': '123456789'}

```

with the templatetag:

```python
from django import template
from django.utils.safestring import mark_safe
import json

register = template.Library()


@register.simple_tag(takes_context=True)
def json_summary(context):
    json_str = json.dumps(context["data"])
    return mark_safe(json_str)
```

## Tasks

### Backend

#### `ObjectsAPIOptionsSerializer`

This contains the registration backend configuration specific to a particular form. It overrides the configuration at the global level. 

- [ ] Add a text field `content_json` which will contain the 'json', i.e. json but with Django template syntax.
- [ ] Add a validation to check that when this 'json template' is rendered, it generates valid json.
- [ ] Since we are loading a json coming from user input, we should limit the size of the template (see warning in https://docs.python.org/3/library/json.html#module-json).


#### `ObjectApiConfig`

This contains the global registration backend configuration.

- [ ] Add a text field `content_json` which will contain the 'json', i.e. json but with Django template syntax.
- [ ] Add the same validation as for the above 'json template'.
- [ ] Same thing about limiting the length of the 'json template'.
- [ ] Add a default 'json template'. This should generate objects with the same structure as now. The default template can be added in a similar way to how the default email templates are added for the email registration backend (see `EmailConfig`).

#### Template tags

- [ ] A tag to render the form data called something along the lines of `nested_json_summary`. This should render the data in the same way as `render_json` (https://github.com/open-formulieren/open-forms/blob/2.1.3/src/openforms/registrations/contrib/objects_api/plugin.py#L131) currently renders the data.

#### Plugin 

These are the changes that should happen on the plugin itself, when it constructs the object that will be sent to the Object API. 

- In the method `register_submission`, `record_data` (https://github.com/open-formulieren/open-forms/blob/2.1.3/src/openforms/registrations/contrib/objects_api/plugin.py#L172) needs to change. A new method should construct the object. This method should:
	- [ ] Decide which 'json template' should be used: the one specific to the form or the global one.
	- [ ] Render the template. It should add the relevant variables to the context (see what the base context contains for the email registration backend: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/registrations/contrib/email/plugin.py#L66). In addition, there should be variables for the URLs of the attachments, the PDF report and the CSV report (in the `register_submission` method, these are `attachments`, `document["url"]` and  `submission_csv_document["url"]`). Make sure that when the final json is loaded, we limit its size (see warning of the json python library about untrusted json).
- [ ] Add a method `get_custom_templatetags_libraries` to register any templatetag specific to this registration backend.


### Frontend (admin)

- [ ] Use a textarea widget for the `content_json` field (this can be configured like for the email registration backend openforms/js/components/admin/form_design/registrations/index.js). Check that the field is wide enough.

### Documentaion

- [ ] Document which template tags can be used and what do they output.
- [ ] Document which variables are available (form/user defined/static).
- [ ] Document how the template can be configured (globally and per form).
- [ ] Add some examples

**Comment by joeribekker** [comment]
This should be the default template after migrating to the new code:

```
{
  "data": {% json_summary %},
  "type": "terugbelnotitie",
  "bsn": "{{ auth_bsn }}",
  "pdf_url": "{{ submission.pdf_url }}",
  "attachments": [
   {% for attachment in submission.attachments %}
     "{{ attachment.url }}"{% if not forloop.last %},{% endif %}
   {% endfor %}
   ],
  "submission_id": "{{ submission.uuid }}",
  "language_code": "{{ submission.language_code }}"
}
```

The new template should also be supported:

```
{
  "bron": {
    "naam": "Open Formulieren",
    "kenmerk": "{{ submission.uuid }}"
  },
  "type": "terugbelnotitie",
  "aanvraaggegevens": {% json_summary %},
  "taal": "{{ submission.language_code  }}",
  "betrokkenen": [
    {
      "inpBsn" : "{{ auth_bsn }}",
      "rolOmschrijvingGeneriek" : "initiator"
    },
  ],
  "pdf": "{{ submission.pdf_url }}",
  "csv": "{{ submission.csv_url }}",
  "bijlagen": [
    {% for attachment in submission.attachments %}
      "{{ attachment.url }}"{% if not forloop.last %},{% endif %}
    {% endfor %}
  ]
}
```

In a later stage, we'll support `{% for betrokkene in submission.identities %}` to get gemachtigde and more.

**Comment by joeribekker** [comment]
Refinement: Eerste versie in komende release maar moet daarna (waarschijnlijk) reworked worden EN er moet gekeken worden naar JSON-templating.
