### ISSUE TITLE
Findings Ooievaarspas

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2888]
### Product versie / Product version

2.1.0

### Omschrijf het probleem / Describe the bug

The form is on our test environment

# Bugs found

## High importance

- [x] More errors inside repeating groups (DH349) => Due to the migration to change `inlineEdit` from `True` to `False` not being run since the form was exported from 2.0.1
- [x] Error messages inside repeating group (DH 308) => Same reason as above
- [x] Can't select 'previous page' button with keyboard navigation https://github.com/open-formulieren/open-forms-sdk/pull/377
- [x] Observed when filling in the step "Uw inkomsten". Sentry 327313 `TypeError object of type 'type' has no len()`. => Caused by the combination of a file attachment and a hidden repeating group in a step https://github.com/open-formulieren/open-forms/pull/2891
- [x] TypeError: 'int' object is not iterable => Caused by the combination of a file attachment and a repeating group with a number field https://github.com/open-formulieren/open-forms/pull/2892
- [x] Negative numbers with currencies don't work (step Bezit en Schulden => select Betaal- en spaarrekeningen in the first question) => This is just configured wrong in the form. The checkbox "Allow negative numbers" is not checked. 
- [x] https://github.com/open-formulieren/open-forms/issues/2912

## Medium importance

- [x] #2889
- [x] https://github.com/open-formulieren/open-forms/issues/2907
- [x] https://github.com/open-formulieren/open-forms/issues/2909
- [x] Heic files cause problems in upload widget https://github.com/open-formulieren/open-forms/issues/2911
- [x] BSN number validates on change instead of on blur https://github.com/open-formulieren/open-forms/pull/2896
- [ ] https://github.com/open-formulieren/open-forms/issues/2924

## Low importance
- [ ] Content field colours not working https://github.com/open-formulieren/open-forms/issues/2895
- [x] Error in console about Type error: this seems like intended behaviour when the functionality to prefill streetname + city is not configured correctly: https://github.com/open-formulieren/open-forms-sdk/blob/main/src/formio/components/TextField.js#L53
- [ ] Crash in logic logging 1: sentry 324246 `TypeError: introspect_json_logic() takes 1 positional argument but 3 were given`
- [x] Crash on logic rule logging 2 https://github.com/open-formulieren/open-forms/issues/2893
- [ ] https://github.com/open-formulieren/open-forms/issues/2902
