### ISSUE TITLE
Als minderjarige kan ik geen verhuizing doorgeven op basis van een uitgevoerde leeftijdscheck.

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#294]
Eis: Authenticatie En Basisgegevens 3d.
Zie ook NvI: 27, 176

This also depends on "stopping" a form, as described in #233 

The idea is that a logic rule can be defined that says: if the date of birth (from prefill) is greater than `$currentDate - 18 years` -> then block the submit button.

**Tasks**
- [ ] Ensure we can use nested jsonLogic triggers
- [x] Add jsonlogic operator to get the current date
- [x] Add jsonlogic operator to compare two dates
