### ISSUE TITLE
Check out the SDK repository and get the environment up and running

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3055]
Epic: #2471

For the UI/UX aspect, the components and building blocks will be developed 100% in Storybook without real backend integration.

Possible backend integration (API calls, dynamic data) can be solved with mocks at the story level.

**Tasks**

- [x] Read and understand the introduction page: https://open-formulieren.github.io/open-forms-sdk/?path=/story/introduction--page, pay special attention to the contributing guidelines
- [x] Clone the SDK repository: https://github.com/open-formulieren/open-forms-sdk
- [x] Bootstrap the environment (`nvm use`, `yarn install`)
- [x] Get storybook running: `yarn storybook`

**Acceptance criteria**

- [x] Storybook runs on your local dev environment
