### ISSUE TITLE
Base form container: set up formik-related tooling

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3056]
Epic: #2471

Users will fill out form data for the appointment. This data/state, metadata and error information must be managed by using the [formik](https://formik.org/) library.

**Tasks**

- [x] Implement a minimal storybook decorator `withFormik` to wrap stories in the `<Formik initialValues={...} enableReinitialize />` component (do not use https://github.com/bbbtech/storybook-formik/, it has an infinite loop bug)
- [x] Add a story using the decorator which leverages the `<Field type="text" as="input" />` component to prove it works, under *Private API / Appointments

**Acceptance criteria**

- [x] Component (stories) can use formik's `Field` component and/or `useField` hook
