### ISSUE TITLE
Base components: Implement text input

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3057]
Epic: #2471

Users will need to fill out some free text, such as their initials, last name and phone number. The appropriate widget for this is a text input.

:warning: This depends on #3056

Note that we use NL Design System components/class names where possible and base building blocks may already be available in the NPM package https://www.npmjs.com/package/@utrecht/component-library-react. It does look like we should be able to use:

```js
import { Textbox } from "@utrecht/component-library-react/Textbox";
import { FormLabel } from "@utrecht/component-library-react/FormLabel";
import { FormFieldDescription } from "@utrecht/component-library-react/FormFieldDescription";

// possibly viable:
import { FormField } from "@utrecht/component-library-react/FormField";
```

See the upstream documentation/storybook: https://nl-design-system.github.io/utrecht/storybook-react/index.html?path=/docs/react-component-form-field-textbox--docs

**Tasks**

- [x] Implement the `src/components/forms/TextField.js` component - using Utrecht's `FormField` should go a long way
    - [x] This includes the wrapper div/component
    - [x] This includes the field label
    - [x] This includes a possible field description
- [x] Add a section in Storybook under *Pure React Components / Forms / TextField* to document the component
- [x] Add interaction tests for the story/stories

**Acceptance criteria**

- [x] Looks identical to [equivalent Form.io component](https://open-formulieren.github.io/open-forms-sdk/?path=/story/form-io-components-textfield--default-story)
- [x] Accessible implementation - the input can be filled via the label (click)
- [x] Can be styled primarily using the (NL Design System) design tokens, only absolutely essential CSS is added
