### ISSUE TITLE
Als beheerder kan ik gegevens, gelet op de AVG, anonimiseren en/of verwijderen na een in te stellen periode. Zowel ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#306]
...generiek als per formulier.

Eis: Authenticatie En Basisgegevens 6a.

**Tasks**

* [x] Add admin setting to set cleanup period in days, for successfully sent submissions (if backend is selected - if not, then we do not cleanup) - default = 7
* [x] Add admin setting to set cleanup period in days, for incompleted submissions (regardless of registration backend) - default = 7
* [x] Add admin setting to set cleanup period in days, for submissions that errored sending to backend - default = 30
* [x] For each setting above, add a pulldown to select "delete permanently" (default) or "make anonymous"
* [x] For each setting above, allow to override these per form in the admin
* [x] Add checkbox to each form field to mark that field as privacy sensitive.
* [x] Delete should really delete submissions
* [x] Make anonymous should remove KvK and BSN from submission and clean each field marked as privacy sensitive.
* [x] Add admin setting to set cleanup period in days, to permanently delete submissions, whatever the status - default 90 days.
