### ISSUE TITLE
Base components: implement dropdown/select

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3061]
Epic: #2471

The available products will be present in a dropdown, which must be searchable by the user for the best UX.

Implementation wise, this should be almost a carbon copy of https://github.com/open-formulieren/formio-builder/blob/main/src/components/formio/select.tsx#L30 - but note that ideally the Utrecht component design tokens should be supported/compatible: https://nl-design-system.github.io/utrecht/storybook-react/index.html?path=/docs/react-component-select--docs

We deliberately do not commit to the current Formio styles for this, as it uses the underlying choices.js library which is peculiar and has a number of known (accessibility) issues.

**Tasks**

- [x] Implement the `Select` comopnent
    - use react-select
    - Do 'borrow' the implementation in the `@open-formulieren/formio-builder` library. In the future, these libraries shall converge
    - [x] Ensure the label/description are included
- [x] Add a section in Storybook under *Pure React Components / Forms / Select* to document the component
    - [x] Story: static dropdown options
    - [ ] Story: dynamic dropdown options (use a mock for the API call)
- [x] Add interaction tests
    - [x] User can click the label/open the dropdown and select an option
    - You can borrow the interaction tests/utilities from the formio-builder repository again

**Acceptance criteria**

- [x] Accessible implementation - the input can be filled via the label (click)
- [x] Can be styled primarily using the (NL Design System) design tokens, only absolutely essential CSS is added
- [x] Default Open Forms theme styles are consistent with the other component types / consistent visual identity
- [x] Async capable - possible dropdown options can be provided statically or are retrieved from an API endpoint
