### ISSUE TITLE
Implement the appointment product "unit"

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3062]
Epic: #2471

Relevant design mockup: https://user-images.githubusercontent.com/96970/207066558-bd5b09bc-6805-49db-8ffa-fc6d91c47d10.png

Users must be able to select one or more products/services they wish to make an appointment for. The required input data for this is:

- which product
- for how many people

In pseudo-code, this unit should be composed out of building blocks:

```jsx
<>
  <ProductSelect name={`${namePrefix}.product`} />
  <NumberField name={`${namePrefix}.amount`} min="1" step="1" />
</>
```

The appointment form data should look something alone the lines of:

```js
{
  "products": [
    {
      "product": "166a5c79",  // can be any identifier string
      "amount": 2,
    },
  ],
  "date": "2023-06-01",
  "time": "13:15",
  // ... contact details etc.
}
```

**Tasks**

- [x] Implement the `ProductSelect` component
    - [x] The valid product options are retrieved from an API endpoint
    - [x] Mock the API endpoint, return data has the shape `{code: string, identifier: string, name: string}[]`
- [x] Implement the composite `<AppointmentProduct />` component in `src/components/appointments/`
    - [x] It should take a prop `namePrefix` with an example value of `products[0]` (for the lodash `get` lookups into the formik data)
- [x] Document the component in Storybook under *Private API / Appointments*

**Acceptance criteria**

- [x] Available product options are retrieved from an API endpoint (see https://github.com/open-formulieren/open-forms/blob/769a81b6d8fb30fcbb1453245c8268d5ba39114b/src/openapi.yaml#L178)
- [x] Users cannot provide negative or zero for the amount field
- [x] Users cannot provide non-integer amount values
- [x] Users can type a search box of the product dropdown to narrow/filter the list of options
