### ISSUE TITLE
Step: product selection

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3063]
Epic: #2471

Relevant design mockup: https://user-images.githubusercontent.com/96970/207066558-bd5b09bc-6805-49db-8ffa-fc6d91c47d10.png

Users must be able to select one or more products/services they wish to make an appointment for. The form step should allow them to add and remove additional products. There must always be at least one product/service selected.

:warning: This depends on #3062

**Tasks**

Implement the `ChooseProductStep` component

- [x] Implement an "Add product or service" button, similar to the [repeating group](https://open-formulieren.github.io/open-forms-sdk/?path=/story/form-io-components-editgrid-repeating-group--default-story) component
- [x] Implement removing an (additional) product again
- [x] Document the component in Storybook under *Private API / Appointments / ChooseProductStep*
    - [x] Story: one empty "unit" is visible
    - [x] Story: Click button to add (empty) product/service unit
    - [x] Story: Remove second product/service unit
    - [x] Story: the first unit cannot be removed

**Acceptance criteria**

- [x] Users can select a product and enter the amount
- [x] Users can add an additional product
- [x] Users can remove additional products
- [x] Users cannot remove the "first" (and only) product
- [x] Design is consistent with "Repeating groups" component
- [x] Stories/functionalities have interaction tests
