### ISSUE TITLE
Het gebruik van DigiD eist dat er jaarlijks een zogenaamde DigiD audit wordt uitgevoerd op de omgeving van de ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#307]
...oplossing. De DigiD audit is een deelverzameling van eisen van de BIO.

Eis: Authenticatie En Basisgegevens 6b.

**Tasks**

* [x] DigiD preproductie test door Logius aanvragen
* [x] DigiD preproductie test akkoord door Logius
* [x] TPM aanvraag gedaan bij auditor
* [x] TPM akkoord door auditor
