### ISSUE TITLE
De gebruiker ziet bij de start van een formulier een melding dat er een storing is bij het gekoppelde systeem ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#313]
...waardoor de afhandeling mogelijk vertraagd is.

Eis: Afhandeling 3.
Zie ook NvI: 180

**Verduidelijking**

~We zullen per registratiebackend plugin een health-check in moeten bouwen. De default is gewoon Ja (`return True` -- immers, e-mail is bijna niet te checken, en servicebus ook niet) maar ik vermoed dat we voor StUF-ZDS, ZGW en Melddesk best een periodieke (Celery beat) taak kunnen maken die van elke plugin de health-status bijhoudt in een tabel, en deze meegeeft aan de formulier API.~

Het gaat hier om het tonen van een "mooie" foutmelding als authenticatie systemen niet beschikbaar zijn. DigiD geeft bijvoorbeeld een 500, dan niet Open Formulieren tonen "Vanwege een storing kunt u dit formulier op dit moment niet invullen. Probeert u het later nog eens."

**Tasks**

- [x] Backend (done in #434)
- [x] Frontend that shows the message (https://github.com/open-formulieren/open-forms-sdk/pull/26)

**Vraag aan gemeenten**

- [x] Wat moet de concrete tekst zijn van de melding als een gekoppeld systeem niet beschikbaar is?
- [x] Is een periodieke controle om de 5 minuten voldoende?
- [x] Gaan jullie akkoord dat de accuraatheid van deze melding afhangt van de gekoppelde systemen?
