### ISSUE TITLE
Als beheerder weet ik dat de geboortedatum in het juiste STUF opmaakformaat aan de backoffice applicatie ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#315]
...wordt doorgegeven.

Eis: Afhandeling 5.
Zie ook NvI: 181

**Tasks**

We moeten ondersteunen dat een onvolledige datum uit de BRP kan worden geprefilled in een formulier, en dat deze juist wordt doorgezet als StUF-datum in berichten. Bijvoorbeeld: `<BG:geboortedatum StUF:indOnvolledigeDatum="V">{{ initiator.geboortedatum }}</BG:geboortedatum>`

- [ ] In Open Formulieren gebruiken we dan gewoon een tekstveld t.b.v. prefill geboortedatum dus hoeft niks mee gedaan te worden.
- [x] Wel moet `json2soap_date` kunnen omgaan met onvolledige data.
- [x] En het `StUF:indOnvolledigeDatum` moet in de SOAP-template gezet worden.

Zie: https://github.com/open-formulieren/open-forms/blob/c76059a4ae662165e522cf4ccca4ae3bfd2f0154/src/openforms/registrations/contrib/stuf_zds/plugin.py#L48

**Comment by Bartvaderkin** [comment]
Note this input expects a certain format so if this is user-editable we still needs a custom field that enforces correct format.

Eg: `yyyy-mm-dd`, `yyyy-mm` and `yyyy`
