### ISSUE TITLE
Als beheerder weet ik dat ingevulde formulieren in PDF-formaat worden aangeboden aan het gekoppelde backofficesysteem/zaaksysteem. ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#316]
... ~Daarnaast moeten de in het formulier ingevulde gegevens in de vorm van gestructureerde data worden aangeleverd zoals ExtraElementen bij ZDS, StUF-EF, XML of JSON via bestandslocatie of via de Objectenregistratie (in ontwikkeling).~

Eis: Afhandeling 6.
Zie ook NvI: 182

Doorgestreepte deel is afgesplitst in #430

**Tasks**

- [x] Convert the submission data to PDF (see #241)
- [x] Attach the PDF as document to StUF-ZDS registration backend plugin (it's now a JSON-file)
- [x] Attach the PDF as document to ZGW API registration backend plugin (it's now a JSON-file)

The same PDF should also be used in #241
