### ISSUE TITLE
Allow setting custom timeout values for services

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3164]
### Product versie / Product version

any

### Omschrijf het probleem / Describe the bug

**Bug:** 
nopolder 58
Registration task fails when submission includes multiple large attachments.

Tested on problematic service that fails when multiple large attachments were included. increasing the timeout from 10s to 30s solved the issue and registration task completed with no issues.

**improvement:**
Not all services are created equal, and some services might need some more time to proces incoming data (like dealing with attachments in zaken) then others. 

At the moment requests get a 10s timeout from [base.py](https://github.com/open-formulieren/open-forms/blob/5d0a3b8043ba7725721733e953ce492f42bfa52e/src/openforms/conf/base.py#LL579C1-L579C25)

Allowing services to have their own timeout value instead of the default 10s would prevent these services from timing out when a large request is made.

**Tasks**

* [ ] Add environment variable to set timeout for document requests; default=60s
* [ ] Change ZGW document requests to use above timeout
* [ ] Change StUF-document requests to use above timeout
* [ ] Change Objects API document requests (Document API) to use above timeout
* [ ] Change Sharepoint attachment requests to use above timeout

**Comment by joeribekker** [comment]
Refinement: Added tasks and discussed a timeout-type-key mapping to configure various types of requests and their default timeout. Also, timeout for attachments might need to be calculated based on attachment size. For now, we use the quick way and just increase the timeout for the issue at hand.

**Comment by LaurensBurger** [comment]
additional note 2: a related issue occurred but the scenario was different, in this case the submission contained 24 small attachments of approx 200kb.
While all upload were successful but the user got a 502 because the uploads were not completed within 60s.
Perhaps the timeout should be dynamically calculated based on attachment count?

**Comment by joeribekker** [comment]
> additional note 2: a related issue occurred but the scenario was different, in this case the submission contained 24 small attachments of approx 200kb.

Sounds weird. Every request gets its own timeout so the number of attachments shouldn't matter?

**Comment by LaurensBurger** [comment]
Perhaps nginx 60s timeout?

**Comment by hlmr-erik** [comment]
It occasionally (with less regularity) it occurs as well on changing tabs where uploads haven't taken place at all; in the case of a tab change the 502 is thrown after about 60sec from a call to `_check_logic`; in the case of sending a form it is after a similar timing with a call to `status?`. ngix does present the error though, but possibly doesn't throw it. A HAR-file where it goes wrong upon sending: 
[error_502.zip](https://github.com/open-formulieren/open-forms/files/12031086/error_502.zip)

**Comment by joeribekker** [comment]
@hlmr-erik that sounds unrelated to this issue. This issue is about async registration background tasks (sending from OF to an external system). I think you are referring to uploads in the form (browser sending to OF).

**Comment by eriktechgrounds** [comment]
The issue upon sending a form (as the latest call in the HAR file, which returns a 502 from ngix) I believe might be related: indeed not so for the issue of navigating to the next tab (that seems more like an internal time-out). None of those issues are about uploading to OF.

**Comment by hlmr-erik** [comment]
The issue upon sending a form (as the latest call in the HAR file, which returns a 502 from ngix) I believe might be related: indeed not so for the issue of navigating to the next tab (that seems more like an internal time-out).

**Comment by alextreme** [comment]
@joeribekker Discussed with @LaurensBurger , could we pick up this enhancement, making it possible to set a longer timeout on the Service where necessary? LV is struggling with the StuF-ZDS integration because of very slow responses...

**Comment by sergei-maertens** [comment]
Refinement: let's add a timeout field to:

- `SoapService`
- `zgw_consumers.Service`
- ... any other `*Service` class

Then make sure the timeout is used when making HTTP calls.
