### ISSUE TITLE
Allow to change registration plugin and or change "zaaktype" with logic

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3179]
Als formulierbouwer wil ik binnen formulieren de mogelijkheid om o.b.v. vragen/validatie/logica, binnen één formulier kan sturen/flowen naar:

* één van meerdere mogelijke zaaktypen
* mailverwerking van het formulier

Zodat ik voor formulieren die o.b.v. een nuance verschil, op input van de burger/of het bedrijf, moeten resulteren in een verschillend zaaktype, of mailverwerking niet meerdere formulieren hoef te bouwen.

**Argumenten**

* In theorie kun je ook flowen middels een beslisboom, maar volgens Haarlemmermeer haalt dit vragen uit de context.
* het is niet wenselijk om meerdere formulieren te hosten met dezelfde naam met een nuanceverschil.

Related: Dimpact PF-82

**Tasks**

* [x] Mogelijkheid tot toevoegen meerdere registratieplugins op een formulier 
* [ ] Mogelijkheid om in logica te kiezen tussen registratieplugin
* [ ] Mogelijkheid om voor bepaald zaaktype te kiezen op basis van logica.
* [ ] Omschrijving kan afwijken op basis van logica regels (maar hier is een ander ticket op)

**Comment by hlmr-erik** [comment]
Voorbeelden, bijv. bepaalde subcategoriën (via dropdown) in het aanvragen van een subsidie leiden naar een ander zaaktypenummer. Sommige aanvragen vallen onder 'tijdelijke subsidie', andere 'eenmalige subsidie', 'prestatiesubsidie' etc. 

Ook bij het formulier voor de aanvraag loonkostensubsidie, gaan deze afhankelijk van een keuze (radiobutton) naar een ander zaaktypenummer, en bij 1 vd keuzes naar een e-mailadres
