### ISSUE TITLE
Als beheerder wil ik dat de hosting voldoet aan de AVG- en Ensia-eisen.

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#323]
Eis: Hosting 5.
Zie ook NvI: 57, 98, 110

**Insteek Maykin**

Voldoen aan de AVG-eisen:

- [ ] ~Verwerkersovereenkomst afsluiten met alle deelnemers (Maykin stelt deze op)~ Wordt elders getracked.
- [x] Zaken als welke gegevens opgevraagd worden, privacy verklaring, cookiemelding/acceptatie ligt bij gemeenten
- [x] Een optie om privacy verklaring te accepteren en te downloaden moet configureerbaar zijn in Open Formulieren

Voldoen aan de ENSIA-eisen:

- [x] We zijn al ISO27001 gecertificeerd.
- [x] Tool op ensia.nl gaat 5 juli live. Daar kijken wat te doen. Dit zal waarschijnlijk een quickscan worden (vermoed BIO BBN 2). Deze tool is voor gemeenten.
- [x] 2-factor auth gaan we toevoegen aan de beheer interface.

**Tasks**

*AVG*

* [x] Add privacy configuration (file and/or link to privacy + text to show on the checkbox label) 
* [x] Add option to add the checkbox + label + link to file/url of the privacy doc) to the form on the summary page (checkbox is mandatory to check).
* [x] See: https://github.com/open-formulieren/open-forms/pull/466#pullrequestreview-699995665

*2FA*

* [x] Add 2FA to admin
* [x] Enforce strong passwords in admin
* [x] Password reset needs to be present
* [x] See: #473

**Comment by joeribekker** [comment]
Besproken met PO: Taken zijn akkoord, rest ligt inderdaad vooral bij gemeenten.
