### ISSUE TITLE
Als beheerder kan ik meerdere domeinen beheren en uitbreiden. Het is mogelijk om nieuwe domeinen toe te voegen ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#325]
...en er kan makkelijk geswitched worden tussen de verschillende domeinen (Multi domein). De inschrijver omschrijft hoe aan deze eis voldoen kan worden, en op welke manier het multitenancy vraagstuk architectuurtechnisch en budgettair opgelost gaat worden.

Eis: Hosting 7.
Zie ook NvI: 57, 98, 106, 110, 114, 115, 184

**Tasks**

Some organizations manage multiple sites (instances of Open Forms). The admins should not need to login to each of the managed sites everytime.

- [x] Add site selectbox (showing configured sites, this can be an environment variable containing a list of URL+domainnames) in admin; on change, redirect user to selected site.
- [x] If user is logged in on current site, automatically login user on the other site (selected in the pulldown)

I see 2 directions:

1. We setup Keycloak and use OpenID-connect for admin logins.

- [x] @sjoerdie Can you install Keycloak on our test environment
- [x] @stevenbal Can you add OpenID-connect for the admin
- [x] @stevenbal Can you connect 2 Open Forms (Duiven and Zevenaar) to this Keycloak instance?

2. We use an OTP-link to switch from one site to another.

If option 1 is not working as intended, we can use this approach.

**Comment by stevenbal** [comment]
@joeribekker I connected https://zevenaar.test.open-formulieren.nl/admin and https://duiven.test.open-formulieren.nl/admin with https://keycloak.test.open-formulieren.nl/auth/. I disabled user registration via Keycloak, so user creation would have to be done via the Keycloak admin

**Comment by sergei-maertens** [comment]
SSO appears to work for me at least :-)
