### ISSUE TITLE
Gemeenten moeten formulieren bijvoorbeeld in workflow engines kunnen gebruiken (zoals Camunda)...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#326]
... ~Gemeenten moeten formulierdefinities kunnen delen en gezamenlijk ontwikkelen.~

Afgesplitst van #245

Eis: Techniek 1.
Zie ook NvI: 51, 79, 108, 163

**Verduidelijking**

Camunda wordt hier bedoeld als registratie backend voor frontend waarin de inzendingen terecht komen zodat Camunda de antwoorden heeft en het proces door kan gaan. Dit is zoals het nu in Utrecht werkt (@sergei-maertens graag confirmatie).

> Gemeenten moeten formulierdefinities kunnen delen en gezamenlijk ontwikkelen.

Dit stukje heeft overlap met #246 

**Tasks**

- [x] Set up Camunda registration plugin boilerplate
    - [x] Boilerplate
    - [x] Add/implement self-checks
- [x] Set up Camunda registration plugin options
    - [x] Process definition
    - [x] Optionally, pin to a particular version of a process definition
    - [x] Define which components/process variables should be injected
        - Flag form field/component as process variable
    - [x] Implement derived process variables: specify the variable name + have the ability to build this up as a complex data-structure (JSON) from components or static/literal values
        - [x] Support objects/lists
        - [x] Support primitives (string, number, bool, null)
        - [x] Support strings with interpolation of form fields
- [x] Implement starting a process instance + storing the instance ID as result

**Comment by joeribekker** [comment]
Ik heb in dit verhaal gemeente Utrecht niet meegenomen. In het perspectief van Den Haag verloopt de Camunda koppeling via de Objecten API maar in het perspectief van Utrecht (van Sergei gehoord) lijkt er een direct koppeling nodig te zijn met Camunda.

Dit laatste behelst het meegeven van variabelen, geconfigureerd per veld met een mooie editor (geen JSON), aan de Camunda API. Hiervoor dient dan een aparte registratiebackend gebouwd te worden.

Het moet verduidelijkt worden in welke scope dit ticket gezien moet worden.

**Comment by LBozarov** [comment]
@joeribekker deze ticket is uit het PvE en ingediend door mij persoonlijk en dus bedoeld zoals scope in Utrecht. Lijkt mij duidelijk. Dus inderdaad koppelen met Camunda is vereist. Dus verhaal van Utrecht moet meegenomen worden.

**Comment by sergei-maertens** [comment]
MVP done, further improvements tracked in #1151
