### ISSUE TITLE
Deprecations to remove in 3.0

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3283]
A list of breaking changes to make when we get to version 3.0

<kbd>CTRL</kbd> + <kbd>F</kbd> on `DeprecationWarning` in the backend to find more.

- ~~INVESTIGATE: can we keep existing endpoints on /api/v2/ and new ones to /api/v3/ so we don't have to move everything at once?~~ Resolving by marking most of the API private API

- Appointments #4872 
    - [x] Remove old-style (form.io based) appointment flow
        - [x] most of `appointments.utils`
        - [x] extracting the appointment data from a submission
        - [x] Frontend code to manage appointment (tab)
        - [x] Remove support for fixed customer fields
    - [x] Remove "invalid input serializer -> return empty result list" in favour of raising a validation error exception
- Formio
    - [x] Remove `fd_translations_converter` module (this will affect exports < 3.0 that have legacy translations) #4828
    - [x] #3718
    - [x] Drop password component #4842
- Form design
    - [x] Remove 'formStep' in location action in favour of `formStepUuid` #4892 
    - [x] Make `FormDefinitionSerializer.name` `readOnly` (name is set via translations) @stevenbal 
    - [x] Delete `_data` model field https://github.com/open-formulieren/open-forms/blob/8f7b003e285893a158036dfc54ffd58f478bd12d/src/openforms/submissions/models/submission_step.py#L102
- Styling/NL DS
    -  [x] Remove compatibility shims from `of-page-header-*` and `of-page-footer-*` in favour of `utrecht-page-header-*` and `utrecht-page-footer-*` tokens @robinmolen 
        - `components/_page-header.scss`
        - `components/_page-footer.scss`
- Registration:
   - [x] Objects API/ZGW groups shouldn't have fields nullable
   - [x] Remove objecttype URL -> UUID import converter hook @robinmolen 
   - ~~Remove document type conversion hook (if it exists)~~
   - ~~Remove documenttype URLs - auto migrate where possible (management command to be added in 2.8.x?)~~
   - [x] Document migration procedures
   - [x] Remove automatic StUF-ZDS Utrecht extension conversion @robinmolen
   - [x] Remove (export/import) support/converter for single-registration backend configuration @robinmolen 

- Authentication
    - [x] Remove legacy machtigen context @sergei-maertens 
    - ~~#4890~~

- Misc
    - [x] Remove `/api/v2/location/get-street-name-and-city` in favour of `/api/v2/geo/address-autocomplete` @robinmolen
    - [x] Normalize API endpoints to use dashes rather than underscores
    - [x] Remove OR filtering in the FD endpoint: https://github.com/open-formulieren/open-forms/pull/3542
    - [x] Remove the null=True from `TemporaryFileUpload.submission` FK @sergei-maertens

**Comment by SilviaAmAm** [comment]
There is also the "old" cosign, but I don't know if we want to remove it afterall

**Comment by sergei-maertens** [comment]
> There is also the "old" cosign, but I don't know if we want to remove it afterall

Good shout - we can discuss that at some point. I think it depends a bit on who's actually using it?

**Comment by sergei-maertens** [comment]
@vaszig you can pick up removing the old appointments integration

**Comment by stevenbal** [comment]
> Objects API/ZGW groups shouldn't have fields nullable

@sergei-maertens the only field that is nullable from what I can see is `objects_api_group` in ZGW registration options: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/registrations/contrib/zgw_apis/options.py#L114

Should this be required?

**Comment by sergei-maertens** [comment]
> > Objects API/ZGW groups shouldn't have fields nullable
> 
> @sergei-maertens the only field that is nullable from what I can see is `objects_api_group` in ZGW registration options: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/registrations/contrib/zgw_apis/options.py#L114
> 
> Should this be required?

I see the following nullable fields that shouldn't be:

* `ObjectsAPIGroupConfig.objects_service`
* `ObjectsAPIGroupConfig.objecttypes_service`
* `ZGWApiGroupConfig.zrc_service`
* `ZGWApiGroupConfig.drc_service`
* `ZGWApiGroupConfig.ztc_service`
