### ISSUE TITLE
Server side redirects to the frontend break when the SDK uses hash based routing

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3362]
### Product versie / Product version

latest, 2.2.x, 2.1.x

### Omschrijf het probleem / Describe the bug

The backend uses deep-links at times (submission resume, redirect back after authentication, change appointment and possible other cases) to the form on the frontend. It does this by taking `submission.form_url` and modifiying the URL with additional path segments and/or query string parameters. `submission.form_url` is recorded when a submission is started and is the only way to know where the public URL of the form is.

However, when you enable hash-based routing, the backend does not know this. Redirects are broken in those situations, as hash-based routing is typically used when embedding forms in a CMS where defining catch-all routes for a particular form is not (reasonably) achievable.

E.g. a form can be available on:

* example.com/formulieren/foo
* example.com/formulieren/foo#/

Possible solutions:

* use some other form of input (query param, possibly HTTP header within the redirect response) to indicate which "route" or action is desired (`/stap/bar`, `/afspraak-annuleren`, `submission-start` etc.). This would decouple the backend from the specific routing solution AND any client-side URLs
* record the routing type during submission creation so that the backend can generate the appropriate URLs

### Verwacht gedrag / Expected behavior

Server side redirects work in both cases.

### Screen resolution

None

### Device

None

### OS

None

**Tasks**

- [x] Implement building redirect URL in backend
- [x] Update SDK to interpret backend actions & action args
- [ ] Add data migration to clean `submission.form_url`
- [ ] Deprecate "cleaned_form_url" wrapper.

**Comment by joeribekker** [comment]
Refinement: Maykin will be stakeholder on this.
