### ISSUE TITLE
Allow configuring checkboxes (privacy, statement of truth) per form

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3372]
Discussed with the stakeholder.

Currently the privacy and declaration of truth checkboxes are configured globally, but not every checkbox is equally applicable to every form. We've decided that the actual texts remain global configuration, and whether they're enabled or not can be configured globally (the default) or have per-form overrides.

**Tasks**

- [x] Add checkboxes configuration part to form designer, dropdown with 3 options: use global config, enable, disable
    - [x] This must be done for each of both checkboxes
- [x] Update validation serializers to take form-specific config into account
- [x] Include checkboxes configuration as part of the form serializer
- [x] With the above, the API endpoint for global configuration can be deleted, as we should always fetch this from the form configuration.
