### ISSUE TITLE
Escape "special" characters when saving data in the Objects API

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3481]
*Disclaimer: Conceptually, I'm against - what I find - unnecessary escaping, just to make sure OTHER applications do not make mistakes but Den Haag wants this, so we add optional support for it.*

Currently, when you have a form with a textfield, let's say "name", and you fill in `<script>alert();</script>`, this value is eventually sent as-is to the Objects API. For example, the Objects API will have data like this:

```json
{
  "data": {
    "name": "<script>alert();</script>"
  }
}
```
Although in Open Forms, there is no problem whatsoever, an external application reading this data *might* interpret this as HTML and show an actual alert-box in the browser.

To prevent this, ~the external application should be fixed~ we need to store the data in the Objects API, with HTML-characters escaped, like this:

```json
{
  "data": {
    "name": "&lt;script&gt;alert();&lt;/script&gt;"
  }
}
```

So, we'll introduce an environment variable `ESCAPE_REGISTRATION_OUTPUT` that will perform HTML escaping on all data sent to the Objects API. By default the value should be `False` (ie. no escaping).

**Tasks**

* [ ] Add `ESCAPE_REGISTRATION_OUTPUT` environment var/setting, default `False`
* [ ] Use `html.escape` to escape all **form** values, passed to the Objects API.
* [ ] BONUS points: Add this in such a way, it works for ALL registration output.
