### ISSUE TITLE
Wensen zonder stakeholder

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3499]
Wensen van Maykin zonder expliciete stakeholder

* [ ] Digest mail met "issues" (rationale: meer zekerheid of alles werkt zoals het moet)
* [ ] Cookie-banner wegklikken niet de pagina laten herladen (rationale: betere user experience)
* [ ] Koppelen met meerdere identity brokers voor beheer (rationale: functioneel beheer toegang scheiden van technisch beheer toegang)
* [ ] Embedding in CMS-en verbeteren (rationale: de customer journey kan zoveel fijner - hash-based routing, origin policy, wordpress-plugin official maken, dingetjes)
* [ ] Formulieren delen met de community (rationale: eenvoudiger gebruik maken van elkaars werk)
* [ ] Configuratie statistieken inzien en aggregeren (rationale: inzicht welke functies worden wel/niet gebruikt voor ontwikkelfocus)
* [ ] Certificaten controle is nu flaky (rationale: beheer annoyance - chain, geen chain, wat checken we met elkaar, werking is onduidelijk en er is geen vinkje of het werkt)
* [ ] Beheer interface moet sneller (rationale: betere user experience - LV duurt 20s komt vooral door herbruikbare stappen)
* [ ] Meer zekerheid over het opslaan van formulieren (rationale: mensen zijn nu bang dat hun werk kwijt raakt - foutmelding die niet juist zijn - is het dan wel opgeslagen, etc.)

**Comment by alextreme** [comment]
Vught 64 -> de daily-digest zou uitgebreid moeten worden met de mislukte inzendingen via stuf-zds, ook bij DH zou dit een stuk meer zekerheid geven
