### ISSUE TITLE
As municipality I want to map form fields/vars to Zaak.eigenschappen in the registration backend

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3600]
... so we can make use of the eigenschappen at all.

ref: Utr 139

Some discussion about making this generic is in order.

**Tasks**

* [x] Create a custom React form (like the Camunda form) for the ZGW API Registration details (in form > registration tab)
* [x] Add an array of (eigenschap, variable) to the form
* [x] You should be able to type the eigenschap-naam (no smart selecting here), and you should select a variable from the list of all variables (this is a re-usable React component)
* [x] You should be able to add and remove items from the array (plus-icon, trashcan)

**Comment by vaszig** [comment]
After some investigation there a couple of approaches:

**1. Work with existing data (fetch `eigenschappen` from the `statustype`)**

- we already retrieve the `statustypen` and show them as a list
- retrieve all the `eigenschappen` from the selected `statustype`
- select the `eigenschap`
- create the `zaakeigenschap` based on the selected-saved `eigenschap` and after the `zaak` has been created
- additional requests: 2

**2. Free to user (create a new `eigenschap`)**

- based on the selected-saved `zaaktype`, create a new `eigenschap`
- validation against the provided fields-values?
- based on the response and on the created `zaak`, create a new `zaakeigenschap`
- additional requests: 2

**Comment by joeribekker** [comment]
Discussed with Sergei: Review from Silvia needed to be eligable for merging in 2.5.0
