### ISSUE TITLE
Improve login screen and process

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3695]
### Thema / Theme

Admin

### Omschrijving / Description

The login process is suboptimal. 2FA is globally set but when using OIDC this should be decided by the OIDC-provider. If OIDC is used, you can still use local accounts. This should be discouraged visually.

**Tasks**
 
* [x] Update the two-factor library to use upstream version again
* [x] Differentiate between OIDC-login and regular logins whether to use 2FA or not (thus, make sure this is not some global setting but based on the session that holds the login-backend information). This probably require library code changes or some custom code in Open Formulieren.
* [x] Make the Django `LOGIN_URL` an environment variable, and document it. This allows us to set it to `/oidc/authenticate/` to automatically go to OIDC provider instead of showing the regular login form.

2FA upgrade is also required for #3049

**Comment by sergei-maertens** [comment]
Need to handle the auto-redirect/`LOGIN_URL` envvar aspect
