### ISSUE TITLE
Adding 2 fieldsets cause the second fieldset to inherit all fields contained in the first fieldset. 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3761]
### Product versie / Product version

master (54991a2f8d51c7a38fcdd7d813a61d4863ad7306)

### Omschrijf het probleem / Describe the bug

Trying to add a couple of fieldsets without saving in between causes satrange behavious. The second fieldset automatically contains all the fields form the first fieldset which looks like:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/227744b7-e63a-4f10-a64b-413a214f2127)

adding a thirst, forth etc. shows the same behavior. 
Saving in between solves the issue.

This affects editgrid too!

### Stappen om te reproduceren / Steps to reproduce

1. Go to the admin to add a new form definition
2. Drag a fieldset **and make sure to change the key**
3. Drag a textfield into the fieldset
4. Add a second fieldset
5. Observe that the text field is also present in the second fieldset

**Tasks**

- [ ] Fix fieldset behaviour
- [ ] Fix editgrid behaviour
- [ ] Verify columns behaviour

**Comment by sergei-maertens** [comment]
I think this is being fixed by 2e0ac45b7deff2f3bc311b0b5c62c7ddcd07ceb1 - need to confirm.
