### ISSUE TITLE
Add statistics view to admin

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3783]
Currently, we cannot reliably show the number of submissions received by Open Formulieren. We can count the submissions present in the database but those are cleaned periodically and should not affect the counter.

**Tasks**

* [x] Add model with attributes: form (fk), form_name (str), submission_count (int), first_submission (datetime), last_submission (datetime).
* [x] Add admin with list view to show these fields. Make a convenience function to show `self.form.name` or `self.form_name`
* [x] Add admin page to form menu (django-admin-index)
* [x] Add hook to update the counter when a submission is successfully finished (not necessarily sent to a register backend but just received by OF)

The idea of the form and form_name fields is that if the form is deleted, we still have the statistics for it.
