### ISSUE TITLE
Allow for a better DMN user experience for both editor and end-user

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3855]
Followup on #3730

**Tasks**

- [x] Extract the available input/output parameters from the DMN XML definition https://github.com/open-formulieren/open-forms/pull/3886 https://github.com/open-formulieren/open-forms/pull/3902
- [x] Show an error in the admin on the modal, when Camunda cannot be reached https://github.com/open-formulieren/open-forms/pull/3912
- [x] Result caching for given input parameters (pure function should be memoizable), though there is a risk the table is updated during multiple execution calls https://github.com/open-formulieren/open-forms/pull/3916
- [x] In the configuration modal, automatically select the plugin if there is only one option available. https://github.com/open-formulieren/open-forms/pull/3923
- [x] Show an error on the form, when a 500 error happened (for example because Camunda is down). Currently, nothing happens and no user feedback (network tab shows a 500). https://github.com/open-formulieren/open-forms-sdk/pull/647
