### ISSUE TITLE
IntegrityError null value in column "prefill_plugin" of relation "forms_formvariable" violates not-null constraint

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3922]
### Product versie / Product version

2.5.x (new form builder)

### Omschrijf het probleem / Describe the bug

when copying a form that contains a textfield a 500 occurs. 
the cause seems to be:
```json
  "prefill": {
    "plugin": null,
    "attribute": null,
    "identifierRole": "main"
  },
```
which is included in new textfields. removing this part from the json fixes the issue in the form builder

**Tasks**

- [x] Do not allow `null` in TS types https://github.com/open-formulieren/types/pull/44
- [x] Fix formio builder to set empty strings as default instead of `null` open-formulieren/formio-builder#127
- [x] Fix backend with data migration to nuke the `null`s and change them into empty string

**Comment by LaurensBurger** [comment]
#3467

**Comment by sergei-maertens** [comment]
I was a bit baffled why this only manifests during copying (and likely import) of a form and not during the normal form editing, but I could find out that the JS actually cleans up these `null` values when creating the variable, which the backend code does not appear to do:

https://github.com/open-formulieren/open-forms/blob/ac70173e71115c2582bf7dedb617e4fde04e9897/src/openforms/js/components/admin/form_design/variables/utils.js#L46

While the backend does:

https://github.com/open-formulieren/open-forms/blob/ac70173e71115c2582bf7dedb617e4fde04e9897/src/openforms/forms/models/form_variable.py#L67

So the backend patch will make this a bit more robust and also add a data/import fix to convert component configurations (again).
