### ISSUE TITLE
Rethink admin Javascript to save a form

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3941]
Currently we perform a bunch of parallel requests in the frontend to save a form after/during editing it: 

https://github.com/open-formulieren/open-forms/blob/ffd32bc0729c80f2a620efb5c4d4dd16c709ff89/src/openforms/js/components/admin/form_design/data/complete-form.js#L394

One big drawback is that the form variables are saved _after_ the form detail call (form create or update), but the registration backends/registration backend options are included in the latter. This means that the validation of registration backend options cannot check for form variables, since they are only saved later, which is not good for our input validation.

There are two options to be explored:

* break the registration backends saving out into its own call
* replace all the individual calls with one big endpoint to save the entire form

**TODO**

- [x] Validation errors on the form tab
- [x] Validation errors on the steps tab
- [x] Validation errors on the registration backends tab
- [x] Validation errors on the literals/translations tab
- [x] Validation errors on the variables tab
- [x] Validation errors on the logic tab
- [x] Validation errors on the confirmation tab
- [x] Validation errors on the submissions tab
- [x] Validation errors on the product tab
- [x] Validation errors on the data pruning tab
- [x] Validation errors on the advanced settings tab
- [x] Ensure auth backends are persisted/submitted
- [x] Ensure payment backend + options are persisted
- [x] Ensure `brpPersonenRequestOptions` advanced options are included in the payload/saved
- [x] Validation errors for service fetch logic

**Comment by joeribekker** [comment]
Refinement: general consensus is to use the big fat endpoint to save everything in 1 transaction:

Benefits:

- Might make import/export better
- Validation can be done in 1 pass
- Complexity is moved to the backend
- Saving will be faster
- More robust saving, better integrity

Downsides:

- Technical uncertaintity
- Will take a while to develop/refactor

**Comment by sergei-maertens** [comment]
Largely covered in #5882, leaving it open to track the integration progress.
