### ISSUE TITLE
Select with multiple: true has wrong default value

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4084]
Currently the form builder produces a default value of `[""]` (i.e. a list with one element - the empty string), which should just be an empty list entirely (`[]`) instead.

This causes validation issues, because the empty string is typically not a valid choice.

**Tasks**

- [x] Patch form builder
- [x] Add data migration (+ form import fixer) to convert `defaultValue: [""]` into `defaultValue: []`
- [x] Check/patch similar components:
    - [x] Radio
    - [x] Selectboxes

**Comment by sergei-maertens** [comment]
Removing backport label - JSON can be edited as a workaround and we're explicitly setting up our backend validation to allow it for now.
