### ISSUE TITLE
DMN improvements for demo

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4269]
Some improvements to the DMN UI

- When selecting a decision definition/table to evaluate, the dependencies in the DRD do not seem to be taken into account
- Consequently, only the inputs of a single table, but not as a whole DRD are taken into account
- Check if we can directly provide the necessary inputs instead of a required decision
- Using `a + b` expressions in an input expression is... uncommon. We don't necessarily need to support this right now.
- Invoking a table for each item in an editgrid (repeating group)?
- Try out -> and relay back error message

Useful resource: https://consulting.camunda.com/dmn-simulator/

**Tasks**

- [x] Update DMN parser in django-camunda to correctly resolve requirements and their inputs - this doesn't seem to go right now
- [x] Add JS library (https://github.com/nikku/feelin/blob/main/src/parser.ts) to parse the FEEL expressions client-side to extract the remaining input parameters.
- [x] Ensure that we can configure variable mappings with implicit parameters (e.g. input with `a + b` FEEL expression -> vars `a` and `b`)

**Comment by sergei-maertens** [comment]
Findings of research done for this ticket:

- Camunda 7.20 implements a part of DMN 1.3
    - It only supports two kinds of boxed expressions: decision table and literal expression. DMN spec itself supports more.
    - It does not support business knowledge models, which is much more advanced and can be used for advanced decision modelling. This *could* be a direction to deal with repeating groups.
    - It does seem to support contexts per decision, but this doesn't appear to be explicitly exposed in the modeller. Untested.
- When a decision has (one or more other) required decisions, then the input parameters of that need to be provided.
    - It does not seem possible in Camunda to evaluate a leaf decision by providing all of its inputs directly, thereby skipping the requirement.
    - Likely evaluating the requirement by itself is possible.
    - Camunda only returns the output of the requested decision, not the outputs of all intermediates (not sure how their playground works then...)
- The DROOLS DMN engine seems more full-featured and can be a nice reference. Way out of scope for here though!
- The Camunda modeler only supports primitive types for inputs, so we have a problem with repeating groups (putting that out of scope for now, it may be solvable in OF rather than at the Camunda level)
