### ISSUE TITLE
CRUD forms next iteration steps

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#437]
#382 is a massive PR, so the next steps will be done in separate pull requests.

TODO:

- ~Form-definition modified warnings~
    - [ ] ~Proper styling for the forms affected by changes to a form definition (modal you see when clicking the link in the warning when you modify a form-definition which already existed)~
    - [ ] ~In the check of forms that will be affected when editing a form definition, the form currently being edited should be excluded~
- Form fields/extra configuration options
    - [x] #546
    - [x] #547
    - [x] Add back the 'Active' checkbox
    - [x] Add back the 'is deleted' checkbox (soft-delete)
    - [x] Add back the 'maintenance mode' checkbox
    - [x] Add the authentication backends selection (#426)
        - The available backends should be retrieved from an API endpoint
        - The backends should be a required field if any of the form definitions are login-required (#417)
    - [x] Add a field to update the text displayed in the submission confirmation page. (#243)
- [x] Add back the JS/CSS snippets fields (see also #405)
- Form definition fields:
    - [x] Bring back the login required checkbox
- [ ] ~Bring back the "save and add another" and "save and continue editing" buttons~
- [x] Fix translations - the React stuff currently has no translations
- [x] Fix product selection and payment configuration (required for the payment flow since a product must be connected for that) (#561)

Striked items are moved to another ticket: #695
