### ISSUE TITLE
AddressNL - overarching epic

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4431]
* Add layout option: `singleColumn` / `doubleColumn` (#4423)
* Validate (or show validation errors) only when a field has been touched (#4420)
* Allow specifying validation regular expressions for nested fields - we can leverage the JSON nature for this:
  
  ```json
  {
    "type": "addressNL",
    "key": "address",
    "label": "Your address",
    "components": {
      "postcode": {
        "validate": {"pattern": "1015 [a-zA-Z]{2}"},
        "translatedErrors": {
          "en": {
            "pattern": "Must be at 1015 XX"
          }
        }
      }
    }
  ``` 
  ![image](https://github.com/open-formulieren/open-forms/assets/5518550/4b780257-6399-46bf-9d5b-c25d92844024)

* #4418
* #4430 
*

**Comment by joeribekker** [comment]
@sergei-maertens can you let your mind go over this. I tried to incorporate all features.

The AddressNL-component features these fields:

A. postalcode, housenumber
B. houseletter, housenumber-addition
C. city, streetname

The letters are referenced in the text below.


## Tasks

* [ ] Add dropdown for "mode" in the component editor, allowing you to choose: Regular, Autofill, Prefill (see Mode-behaviour). This replaces the "adres afleiden" checkbox.
* [ ] Autofill can ONLY be selected if the BAG API is configured. Give an error if its not or hide option completely.
* [ ] Add an option to hide C-fields. By default, they are shown.
* [ ] Add a Prefill-tab to the component editor, allowing you to select a plugin, attribute-set (see Prefill attribute-sets) and source

To discuss: Registration

* [ ] Change the Registration-tab in the componenent editor, allowing to select an attribute-set (see Registration attribute-sets)

--OR--

* [ ] Make sure all A, B and C-fields are shown as variables: `<property name>.postalcode, <property name>.housenumber, ... etc.`
* [ ] Remove the registration tab, and connect them INDIVIDUALLY via the variables-tab

--OR --

* [ ] Make sure the component is shown as variable
* [ ] Optionally add all A, B and C-fields are shown as variables: `<property name>.postalcode, <property name>.housenumber, ... etc.`
* [ ] Remove the registration tab, and connect them AS A SET via the variables


### Prefill attribute-sets:

* KvK: Bezoekadres, correspondentie adres
* StUF-BG/HC BRP: Verblijfsadres
* HC HR: Bezoeklocatie, postlocatie
* Demo: Adres

### Registration attribute-sets:

* StUF-ZDS/ZGW-API's: Initiator verblijfsadres

### Mode-behaviour

In regular mode:

* Show A, B and C-fields as editable (C-fields only if enabled to show)

* If BRK-validation is enabled: Trigger after A and B-fields are filled in.

In Autofill mode:

* Show A and B-fields as editable fields
* Show C-fields as read-only fields
* When A-fields filled in, derive C-fields
* If the C-fields cannot be derived (service offline, invalid address) make the C-fields editable
* If the C-fields can be derived, make the C-fields read-only

* If BRK-validation is enabled: Trigger after A and B-fields are filled in.

In Prefill mode:

* Show A, B and C-fields as read-only
* Prefill allows you to select a plugin and an attribute-set:

* If prefill fails, make A, B and C-fields editable (C-fields only if enabled to show)

* If BRK-validation is enabled: Trigger upon submit/next step

**Comment by sergei-maertens** [comment]
Rough estimate ~8 weeks
