### ISSUE TITLE
Add an (optional) introduction page BEFORE the current form start

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4545]
Taiga DH 662, business case "ondernemers"

For certain forms additional information needs to be displayed **before** the form start page. This page is optional.

Example:

![image](https://github.com/user-attachments/assets/6588d2fb-0816-4a84-abda-d10f20530446)

**Tasks**

- [x] Backend: add "introduction page content" WYSIWYG field and expose it via the form detail API endpoint
- [x] SDK: add additional route for introduction page, redirect there if any content is set from the API, otherwise go to the normal start page
- [x] SDK: new route/component needs to display the content from the backend and include a button that links to the "normal" start page
- [x] SDK: ensure that NL DS styles are applied to WYSIWYG components (headings, paragraph, (un)ordered lists, links)

**Comment by sergei-maertens** [comment]
Refinement: okay to include this in the progress indicator/nav on the right side, navigating back to it doesn't change anything in the submission state (the form start page gives you the option to continue with the existing submission or start a new one)
