### ISSUE TITLE
Specify document type to use in Objects API registration in a more natural way

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4577]
Allow specifying the document type as a combination of `(catalogue, description)` so that the appropriate version can be selected dynamically at runtime.

Split off from #4267

**Tasks**

- [x] Update configuration aspect in backend #4574
    - [x] Add defaults field for catalogue selection
    - [x] Validate the specified catalogue at the model layer
    - [x] Add field(s) for catalogue selection at the form level
    - [x] Validate the specified catalogue at the serializer level
    - [x] Validate that the documenttype URLs are in the specified catalogue (if provided)
    - [x] Allow specifying documenttype references by 'omschrijving'
    - [x] Validate the documenttype with omschrijving exists in the specified catalogue
- [x] Dynamically resolve the correct documenttype to use within the specified catalogue and applicable version (select based on valid from/until combined with the submission completion timestamp) #4578
- [x] Add a feature flag to allow/disallow draft ("concept") document types during validation & registration phase
- [x] Update UI to allow users to use the new configuration
    - [x] allow selecting catalogue in dropdown
    - [x] allow selecting the documenttype in a dropdown
    - [x] Move the existing URL-based fields to a "deprecated" fieldset
