### ISSUE TITLE
Make ZGW registration options consistent with Objects API

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4606]
- [x] Use modal to set registration options
- [x] Use React-Select for dropdowns
- [x] Add catalogus selection (same UI/widget as Objects API)
- [x] Allow selecting zaaktype  by identification
- [x] Allow selecting document type by `omschrijving`
- [x] Allow selecting roltype (for medewerker) in a dropdown
