### ISSUE TITLE
Deprecate (and remove) price logic

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4771]
With #4764 it's possible to point to a variable holding the value of the price, and this essentially makes price logic rules obsolete.

We can automatically migrate these:

* Create a user defined variable for the price
* Configure `form.priceVariableKey` to point to this variable
* For each price logic rule: create a normal logic rule with the same trigger, and as sole action assign the configured price to the price variable

This should also be applied on imports of legacy form exports.

Benefits:

* Less variants to configure for form designers/functional admins
* Unified logic interface
* Code removal! Less code means less code to maintain.

**Tasks**

- [x] Implement data migration to convert price logic rules
- [x] ~~Handle imports by dropping/ignoring price logic rules in export files~~ they never were imported in the first place
- [x] Delete price logic rules from the UI
- [x] Delete price logic endpoints ~~+ database models~~
- [x] Add release notes for export handling + conversion
- [x] Update documentation

**Comment by joeribekker** [comment]
Can be logegd under the same business case as the variable thing for DH.
