### ISSUE TITLE
Outgoing email logging improvements

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4895]
We support sending custom email headers in all emails sent by Open Forms. Currently, this is only used for registration emails. See

https://github.com/open-formulieren/open-forms/blob/dd38e638d1b00101cc37967c897bb3e6a753d991/src/openforms/emails/constants.py#L4

While debugging a production environment to figure out what type of emails were sent, I had to search on the content of the email which is fragile because different forms can use completely different templates rather than a single global configuration. This would've been easier if the registration emails would have been properly tagged with the custom headers so I could filter on this header instead (I was able to exclude registration emails this way).

Additionally, there's a typo in the content type for the `Submission` model - the app label is singular instead of plural.

**Tasks**

- [x] Ensure that custom email headers are used for confirmation emails
- [x] Ensure that custom email headers are used for cosign request emails
- [x] Fix content type for submissions in email constants

**Comment by viktorvanwijk** [comment]
> Currently, this is only used for registration emails

and

> This would've been easier if the registration emails would have been properly tagged with the custom headers 

seem to be contradicting each other. In the code I can find usages of `EmailContentTypeChoices.registration`, but NOT `EmailContentTypeChoices.confirmation` and `EmailContentTypeChoices.cosign_confirmation`. Shouldn't 'registration' be 'confirmation' in the task list, or am I not understanding it correctly?
