### ISSUE TITLE
Add a registration backend that sends the form/submission variables as JSON to some API endpoint

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4908]
There is a desire for a "simple" registration backend/plugin which just dumps the submission/form variables with their values as a "flat" JSON structure and sends this data to an API endpoint for further processing. The goal is to keep this super simple and light weight, and let the post-processing be done on the receiving end (with an enterprise service bus or other technologies).

**Requirements**

- [x] A top level object with keys `values` and (optional?) `schema` is sent
- [x] You can specify which service to send the data to (reference to `zgw_consumers.Service`)
- [x] You can configure which endpoint to send the data to
- [x] For each form variable, you can include/exclude it in the data with a simple checkbox in the variables table
- [ ] #4980

**Example**

An example form with the following configuration:

* Authentication via DigiD, capturing a BSN
* First form step with text fields `firstName` and `lastName`
* Second form step with a user upload `attachment`

Should lead to a JSON object being sent with the shape:

```json
{
    "values":
    {
        "auth_bsn": "123456782",
        "firstName": "Donnie",
        "lastName": "Darko",
        "attachment": "<base64 encoded data>"
    },
    "schema":
    {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "properties":
        {
            "auth_bsn":
            {
                "type": "string",
                "pattern": "^\\d{9}$"
            },
            "firstName":
            {
                "type": "string"
            },
            "lastName":
            {
                "type": "string"
            },
            "attachment":
            {
                "type": "string",
                "contentEncoding": "base64"
            }
        },
        "required":
        [
            "auth_bsn",
            "firstName",
            "lastName"
        ],
        "additionalProperties": false
    }
}
```

**Tasks**

- [x] Define new registration plugin - it's probably wise to gate it behind a `if settings.DEBUG` since I don't expect this to be done for 3.0
- [x] Implement plugin configuration options:
    - Service to use
    - Endpoint to send data to (relative to service API root)
    - Form variables (including static variables!) to include
- [x] Add docker-compose mock service (flask app?) to simulate a receiving server
- [x] Implement sending the data to the configured service in the defined format, taking into account the configuration options
- [x] Add configuration checks to configuration overview
- [x] Ensure that we can generate an appropriate json-schema for each form component type
- [ ] Add tests

**Pointers**

Existing code that can be useful:

* service fetch
* email registration plugin
* objects API registration configuration/options

**Comment by viktorvanwijk** [comment]
> * Optionally, a [JSON Schema](https://json-schema.org/) definition of the submitted data is provided in the schema key

Does 'optionally' mean that the configuration options should also include a checkbox with which you can select this?

**Comment by sergei-maertens** [comment]
> > * Optionally, a [JSON Schema](https://json-schema.org/) definition of the submitted data is provided in the schema key
> 
> Does 'optionally' mean that the configuration options should also include a checkbox (for example) with which you can select this?

No - it's a wish to include this, but having the actual data is the minimum requirement for this ticket. Including the JSON Schema is desired, but not crucial and should likely be the final task of this ticket to implement :)

**Comment by viktorvanwijk** [comment]
@sergei-maertens In the schema, have you left out the `attachment` property from the `required` list on purpose?

**Comment by sergei-maertens** [comment]
> @sergei-maertens In the schema, have you left out the `attachment` property from the `required` list on purpose?

not on purpose!
