### ISSUE TITLE
Remove legacy zaaktype/documenttype URL fields in registration backends

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4939]
Currently we support he indirect references by using omschrijving/identificatie and the legacy explicit version URLs for documenttypes/zaaktypes in the Objects API and ZGW API's registration. The latter can be removed as a cleanup.

**NOTE**

This requires the file upload component URL references to be replaced with documenttype descriptions too, and made context-aware of the registration backend that they're used by (moving out of formio builder into the variables tab).

**Tasks**

- [x] Add detection script/upgrade check blocking upgrades if legacy fields are still used somewhere (#6309)
- [ ] Delete the fields `ZaakOptionsSerializer.zaaktype`, `ZaakOptionsSerializer.informatieobjecttype`, `ZaakOptionsSerializer.objecttype`
- [ ] Delete the fields `ObjectsAPIOptionsSerializer.informatieobjecttype_submission_report`, `ObjectsAPIOptionsSerializer.informatieobjecttype_submission_csv`, `ObjectsAPIOptionsSerializer.informatieobjecttype_attachment`
- [ ] Delete the fields `ObjectsAPIGroupConfig.informatieobjecttype_submission_report`, `ObjectsAPIGroupConfig.informatieobjecttype_submission_csv` and `ObjectsAPIGroupConfig.informatieobjecttype_attachment`

**Comment by joeribekker** [comment]
Estimate: 2 weken

**Comment by sergei-maertens** [comment]
I analyzed our SAAS test and production environments and the conclusion is that barely anyone is using the catalogue configuration on the API group level (Objects API, ZGW). Most select the catalogue in the registration backend options. I can't tell what the situation is for on-prem environments due to not having access.

This layering of catalogue information/defaults leads to a lot of complexity in the code base, and I believe we can safely migrate this automatically, given that:

1. Users are expected to use 3.5 to convert legacy URL configuration into modern configuration (catalogue + references)
2. 4.0 is already known to drop support for legacy URLs, so we can assume we only have to deal with modern configs
3. With no-one known to use legacy URLs (at the API group level), we don't need to do anything about the document description fields. Though, we can hide those in the admin and keep the runtime code from resolving them when they're set as a default, if that makes sense
4. A data migration can copy the group-level catalogue to each registration backend that uses this API group, but only if no explicit catalogue override is specified. Legacy URL migration during 3.5 will likely have populate a bunch already, so we expect this to have negligible impact. Only empty-ish configuration would get updated that relied on defaults, and we can copy all those over.

This makes the migration and future enhancement a lot more manageable, which they currently aren't and block me for #6281

**Comment by sergei-maertens** [comment]
Make sure the copy text here is correct:

<img width="1421" height="76" alt="Image" src="https://github.com/user-attachments/assets/dd332f63-d647-4102-ad07-67a30a186356" />
