### ISSUE TITLE
Registraties bevragen (service fetch) verbeteringen

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4965]
Related stories

* [ ] https://github.com/open-formulieren/open-forms/issues/2697
* [ ] https://github.com/open-formulieren/open-forms/issues/2683
* [ ] https://github.com/open-formulieren/open-forms/issues/2777
* [ ] https://github.com/open-formulieren/open-forms/issues/2873
* [ ] https://github.com/open-formulieren/open-forms/issues/3003
* [ ] https://github.com/open-formulieren/open-forms/issues/3106
* [ ] https://github.com/open-formulieren/open-forms/issues/3409
* [ ] https://github.com/open-formulieren/open-forms/issues/3487
* [ ] https://github.com/open-formulieren/open-forms/issues/3617
* [ ] https://github.com/open-formulieren/open-forms/issues/4200

**Comment by sergei-maertens** [comment]
Estimate: 6-8 weeks.
