### ISSUE TITLE
Implement "design" for sub-domain approach

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#506]
The subdomain approach is the one where we deploy open-forms on a subdomain of the municipality, and forms are hosted on this environment.

The form detail page should not include any bloat (the current scaffolding is a static mock-up) so that end-users aren't confused.

Split off from #181

**Tasks**

- [x] The demo scaffolding must be removed (css, html) The form/list should still be in a container of the current width.
- [x] The homepage (/) of the site should redirect to the gemeente website (ie. we don't show a list of forms anymore) *
- [x] Add option to upload a logo
- [x] Add option to enter a link for the "terug naar gemeentewebsite" link
- [x] Use design tokens to alter the page colors + a template to apply the design tokens
- [x] Include link to cookies settings in footer (see https://github.com/open-formulieren/open-forms/pull/491#discussion_r674079056)
- [x] Include link to privacy policy in footer (see #323)
- [x] Allow the forms to work under a cname dns entry, like formulieren.utrecht.nl

\* If we still want a list, it should only show if logged in as admin and/or we should amend the admin form list with a link action to start the form.
