### ISSUE TITLE
Add production selection (tab) and payment backend/options configuration to React CRUD page

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#561]
Currently, only the vanilla django backend supports these.

In #539, support for payment backends was added, but this is not added yet to the React UI to build forms.

**Tasks**

- [x] Add a tab "Payment"
- [x] Add the payment backend selection as a field
- [x] Add the payment options form as a field, if relevant (see #554) for similar problem with the registration backends
- [x] Ensure merchant can be selected from drop down list
- [x] Add a tab "Product"
- [x] Add a product selection field.
