### ISSUE TITLE
Move appointment configuration to separate form builder tab

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#612]
... rather than having extra FormIO options defined in the different components.

After #573 is merged, we should:

**Tasks**

- [x] Remove custom FormIO component schema items (`appointmentBirthDate`, `appointmentLastName`)
- [ ] Add a field `forms.Form.appointmentconfiguration` (JSONField) where the pointers to the form definition components are stored
- [x] In the UI, present dropdowns to select the appropriate component (re-use the `ComponentSelection` component from the form logic)
