### ISSUE TITLE
Set up async tasks orchestration

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#614]
On submission complete, various tasks happen in a specific order with possible failure states.

The celery task orchestration needs to be defined and work with failure/timeouts to proceed/not-proceed. The different modules that Open Forms has will tap into this.

**Tasks**

- [x] Set up on_submission_completion handler which kicks of a celery chain
- [x] Store root task ID with submission for later checks
- [x] Organize celery tasks with possible timeout/retry behaviour
    - [x] Set up suitable decorator
    - [x] Check all tasks which *may* communicate with external systems
    - [x] Implement unique reference extraction
- [x] #651
- [x] Set up django-timeline-logger to log all events/actions (#247)
- [x] Set up status progression
- [x] Check if we can use a HMAC status check URL & freeze the download report token based on the status
- [ ] Schedule resizing of attachments BEFORE registration backend (parallel group) #507 
- [ ] #701

**Comment by sergei-maertens** [comment]
Far from done :-)
