### ISSUE TITLE
Update documentation for registration backends

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#621]
**Tasks**

- [x] Document (in English) how to configure registration backend: StUF-ZDS
- [x] Document (in English) how to configure registration backend: ZGW APIs
- [x] Document (in English) how to configure registration backend: Objects API
- [x] Document (in English) how to configure registration backend: Mail
- [x] Document (in English) how to configure registration backend: Empty (explain that they are then stored in OF)

See [here](https://open-forms.readthedocs.io/en/latest/configuration/bag.html) for examples
