### ISSUE TITLE
Update documentation for prefill backends

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#622]
**Tasks**

- [x] Add (in Dutch) example form to show prefill (use KvK, since its free to get the API key). See [here](https://open-forms.readthedocs.io/en/latest/manual/forms/examples/autofill_address.html) for example)
- [x] Document (in English) how to configure pre-fill backend: KvK
- [x] Document (in English) how to configure pre-fill backend: StUF-BG
- [x] Document (in English) how to configure pre-fill backend: Haal Centraal Bevragen personen

See [here](https://open-forms.readthedocs.io/en/latest/configuration/prefill/bag.html) for examples

**Comment by Bartvaderkin** [comment]
Note: the StUF-BG and Haal Centraal probably share a lot of text with #621 so once #628 is reviewed and tuned we can copy or link some of this.
