### ISSUE TITLE
When StUF-BG fails the form does not render at all.

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#647]
This happened after logging in with DigiD, when the first page should display some prefilled user information. This needs to be checked in the logs.

**Update**

Current behaviour is this error:

The first step loads until StUF-BG service replies (expected). StUF-BG fails leading to an error in the API response, resulting in an empty first step in the form. Thus,

`/api/v1/submissions/d9dae2ad-dd32-43d8-9705-338e4fd42d65/steps/c8b1f7c7-2fbf-472b-ba39-7914dade5745?`
returns a HTTP 502 due to a Python error: 
```
Traceback (most recent call last):
  File "/app/src/./openforms/prefill/contrib/stufbg/plugin.py", line 62, in get_prefill_values
    data = dict_response["Envelope"]["Body"]["npsLa01"]["antwoord"]["object"]
KeyError: 'npsLa01'
```

caused by this SOAP response:
```
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <soapenv:Fault>
            <faultcode>soapenv:Server</faultcode>
            <faultstring>Policy Falsified</faultstring>
            <faultactor>[snip: stuf-bg-service-url-here]</faultactor>
            <detail>
                <l7:policyResult status="Error in Assertion Processing" xmlns:l7="http://www.layer7tech.com/ws/policy/fault"/>
            </detail>
        </soapenv:Fault>
    </soapenv:Body>
</soapenv:Envelope>
```

**Original**

```
Traceback (most recent call last):
[...]
  File "/app/src/./openforms/prefill/contrib/stufbg/plugin.py", line 61, in get_prefill_values
    data = dict_response["Envelope"]["Body"]["npsLa01"]["antwoord"]["object"]
TypeError: 'NoneType' object is not subscriptable
```

**Tasks**

* [x] Handle Python SOAP-errors in such a way the frontend can continue. For prefill, this means the values can simply not be prefilled.
* [x] This should be logged in Django timeline logger (and in Sentry please with traceback).
* [x] Handle SOAP-Faults (see XML above) specifically to include the faultstring and details in the timeline logger (I thought this was done already but the SOAP-service is spread out a bit over the code).
