### ISSUE TITLE
Implement SDK as client/caller

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#663]
**Tasks**

- [x] Poll the status endpoint received from the submission completion endpoint while status is `in_progress`
- [x] Remove the `retry` result (see [comment](https://github.com/open-formulieren/open-forms/pull/664#discussion_r709219848))
- [x] Stop polling the status endpoint once the status is `done`
    - [x] On success, render the confirmation page
        - [x] Render included confirmation page content
        - [x] Check if a payment URL is included and if payment is required, "start" the payment
        - [x] Display the PDF report download URL
    - [x] On failure, re-render the overview/summary page and display any available error information so the end-user can perform corrective actions
