### ISSUE TITLE
Add columns component to form editor and remove BRP group/components

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#673]
**Tasks**

![image](https://user-images.githubusercontent.com/96970/133610647-b985c748-59b5-4099-b74b-78a8f3b055c0.png)

* [x] Add columns component
* [x] Make sure columns component renders correctly in SDK
* [x] Remove BRP group from editor (since its not used)
