### ISSUE TITLE
Zorg dat het registratienummer (zaaknummer) met de betalingstransactie wordt meegestuurd.

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#674]
The Ogone legacy backend is a bit tricky to get right and send along all the relevant information.

What do we have?

* The registration number (public reference) is stored in the `Submission.public_registration_reference` field. This reference is communicated to the end-user. It is guaranteed to be set because of the async flow handling BEFORE we enter payment.
* For a payment flow, we require a unique order ID (see https://github.com/open-formulieren/open-forms/blob/master/src/openforms/payments/models.py#L45). This must be unique even for multiple payment attempts for the same submission because of Ogone requirements (verified this with Bart).

These two things look similar but they aren't - we cannot use the `public_registration_reference` as the orderId, as with partial/retried payments, this is no longer a unique value.

However, the reference should be sent along as meta information _somewhere_.

**Tasks**

- [x] Check the Ogone documentation for which parameter applies to include this reference
- [x] The reference **must** be stored with the payment in Ogone
- [ ] ~It would be _nice_ if that reference is displayed on the payment page of Ogone~

**Comment by joeribekker** [comment]
The reference can be stored in whatever field is used for payment description (shown on bank statements)

**Comment by Bartvaderkin** [comment]
The reference is saved as "Description" in the payment transaction on Ogone (via the COM parameter).

**Comment by Bartvaderkin** [comment]
- Adding text to the checkout page is not supported in Ogone's responsive template. The classic template is not usable.
- Customizing the logo above the payment page should be possible but requires to use an uploaded file and this is not supported on the Ogone test environment (!). Eg: the LOGO parameter refers to filenames on Ogone's file hosting and you need to use their backend environment to upload it. By default it uses the `logo.png` file and you can replace files in the file manager so theoretically this should work but we cannot test it.

**Comment by sergei-maertens** [comment]
This was done and no further effort on our end is needed.
