### ISSUE TITLE
De gebruiker kan een afspraak wijzigen via een url in een bevestigings e-mail.

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#680]
Eis: Afspraken 3 (deel 2: wijzigen, deel 1 in #263 ).
Zie ook NvI: 60, 92

**Tasks**

* [x] ~Add API endpoint to change the appointment.~
* [x] To change an appointment, we can use the link (open forms, form url) that was used to create the appointment in the first place. So, point the user to the "appointment form"
* [x] The backend should make a copy of the original submission (data) into a new submission, keep a FK reference to the original, and load the new submission in the form
* [x] Improvement over the previous bullet: Allow the pre-selection of a product using a query param: `/form/my-form?product=XYZ` and use this in the change appointment link (see below).
* [x] Keep track that this submission replaces a previous submission (maybe add `Submission.previous_submission`)
* [x] The appoinment plugin behaviour should be adjusted so that when a previous submission is present, the previous submission appointment is cancelled AFTER the new appointment is created.
* [x] For now, we leave out the cancellation/deletion of the previous submission in a registration backend.
* [x] The confirmation email should indicate this concerns a change. Add " (wijziging)" to the end of the subject.
* [x] Add change link to the confirmation email: 
  **Afspraak wijzigen of annuleren**
  o [Ik wil mijn afspraak wijzigen]()
  o [Ik wil mijn afspraak annuleren]()

**Context**

The idea is that we will not implement any real "change" behaviour and call some appointment provider change API endpoint. Instead, we will simply combine "make new appointment + cancel old appoinment" and make the user feel he/she is changing the appointment. 

This choice is made because too much can be changed with numerous side effects that are hard to predict. What if you change the product and a different form fields should be present? Even if the cancel appointment API call fails for some reason, we can still make the new appointment. If a change appointment would fail, it's unclear what the status is exactly.

**Comment by joeribekker** [comment]
I'm removing this from the MVP. It's unclear yet how this will work exactly.

**Comment by joeribekker** [comment]
Decided with @sergei-maertens to implement this similar to the cancel flow. The open issue is to obtain the URL where the SDK is hosted, this should be available now however.
