### ISSUE TITLE
Als beheerder wil ik een overzicht zien welke plugins goed of fout zijn geconfigureerd

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#688]
**Tasks**

* [ ] Add `def test_config(..)` to `openforms.registrations.base.BasePlugin` as abstract method
* [ ] Implement this `test_config` function for the `...zgw_apis.plugins.ZGWRegistration` plugin to test if the configuration is valid
* [ ] The configuration is valid if the `ZgwConfig.get_solo()` has valid parameters (and exist at all) and it's possible to retrieve the configured `zaaktype`, and other configured URLs
* [ ] Add an admin view `/admin/config/` in the layout of the admin to show the status of this plugin with the columns: label, plugin name, `test_config` result shown as "true/false/n.a." icon (see admin boolean field).
* [ ] Add a test that tests this function for this particular plugin

When done:

* [ ] Repeat the above for all registration plugins.
