### ISSUE TITLE
Als gebruiker wil ik nette e-mails ontvangen

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#708]
In different user stories, different e-mail approaches are used for various features. These should be 

**For users**

* [x] Confirmation e-mail
* [ ] ~Notify suspension (tussentijds opslaan)~

**For admins**

* [x] Registratie backend email (initial)
* [x] Registratie backend email (payment)

**Tasks**

* [x] Make a base template for all emails. Make the email as simple and low-tech as possible to prevent rendering issues in various email clients.
* [x] Refactor template tags to be more straightforward (see example below)
* [x] The basic styling used for the website should be taken into account for emails (logo, footer color, etc.)
* [x] Update any default mail bodies to match the new tags and styling if needed.
* [x] Make basic validation by attempting to render the mail and if it fails just give a generic error message (invalid mail template). See as example: https://github.com/maykinmedia/mail-editor/blob/e9ea1762af9a5c7ec0826876cb647dea444b95ba/mail_editor/mail_template.py#L81
* [x] Validate that appointment and payment tags are included always, for confirmation email
* [x] Update the HTML content markup to example below
* [x] Match HTML email style with general Open Forms style
* [x] Do something to make text versions functional/acceptable (eg: links, tables, whitespace etc)
* [x] Document which styling is used from the design tokens in emails

\* The confirmation email template tags should be streamlined to be as easy to use as possible. Currently, it's a bit unintuitive to create a template: https://open-forms.readthedocs.io/en/latest/manual/templates.html#confirmation-email

The default mail template (in the admin, not the html template) could look like this
```
Geachte heer/mevrouw

Wij hebben uw inzending, met referentienummer {{ public_reference }}, in goede orde ontvangen.

{% summary %}

{% appointment_information %}

{% payment_information %}

Met vriendelijke groet,

Open Formulieren
```

The above should be enough to render everything needed. The result should be something like (without the odd table headers, but with nice "headings" for each section if there is any data!):

---

Geachte heer/mevrouw

Wij hebben uw inzending, met referentienummer OF-1234, in goede orde ontvangen.

**Samenvatting**

Veld | Uw invulling
--- | --- 
Voornaam | John
Achternaam | Doe

**Afspraak informatie**

U heeft een afspraak op maandag 12 oktober 2021 om 11:00 op lokatie hoofdkantoor.

Veld | Uw invulling
--- | --- 
Adres | Teststraat 1, Amsterdam
QR-code | ![image](https://user-images.githubusercontent.com/96970/137486647-f8163212-336e-44d3-ba88-a341911f81cf.png)

* [Afspraak annuleren](#)
* [Afspraak wijzigen](#)

**Betaal informatie**

U heeft nog niet betaald. De totale kosten zijn EUR 30,00.

* [Openstaande bedrag betalen](#)
