### ISSUE TITLE
Show payment result in the SDK after the payment flow exited.

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#724]
Payment flow can be exited succesfully or with errors - both cases need to be handled.

The backend redirects the user back to the form that initiated the payment. Currently, it renders a blank new start-form instead of
a nice confirmation|error page with proper feedback.

**Task**

- [x] Check how the backend redirects the user back
- [x] Implement the necessary routes in the SDK
- [x] Handle success
- [x] Handle failure/cancel/aborted status
