### ISSUE TITLE
Add the submission PDF to be sent as CSV when using the email registration plugin

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#757]
**Tasks**

* [x] In the email registration plugin, add support for adding the submission to be sent as CSV (currently, it's just the PDF)
* [x] Add configuration option to "Registratiebackend" in the admin, when selecting the e-mail option, to indicate in what format the submission attachment should be sent.
* [x] If possible, re-use the existing CSV/Excel export for submissions.
* [x] If possible, allow multiple file attachments (PDF and Excel - so checkboxes in the config page) to be sent with the email registration mail.
