### ISSUE TITLE
Pass geo-coordinates from the map component to the registration backend

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#790]
You can connect fields to a registration field in the builder. The mappings should be added for the registration backends below.

**Tasks**

* [x] Implement StUF-ZDS (zaak-geo) fields (in eerste instantie toevoegen via extra elementen \*)
* [x] Implement ZGW API (zaak-geo) fields
* [x] Implement Object API (object-geo) fields

Did I miss any?

\* StUF-ZDS 1.x kent geen zaakgeometrie. Ik zie het ook niet in StUF-ZKN 3.10. [Het zit wel in RGBZ 2.0](https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/attribuutsoort/zaak.zaakgeometrie).

Het kan zijn dat `anderZaakObject.lokatie` hiervoor bedoeld is:

```xml
            <ns:anderZaakObject>
               <ns:omschrijving StUF:noValue="?" StUF:exact="true">?</ns:omschrijving>
               <!--Optional:-->
               <ns:aanduiding StUF:noValue="?" StUF:exact="true">?</ns:aanduiding>
               <!--Optional:-->
               <ns:lokatie xlink:type="simple" xlink:href="?" xlink:role="?" xlink:arcrole="?" xlink:title="?" xlink:show="?" xlink:actuate="?" gml:remoteSchema="?" StUF:noValue="?" StUF:exact="true">
                  <gml:_Surface gml:id="?" gid="?" srsName="?" srsDimension="?" axisLabels="?" uomLabels="?">
                     <!--Zero or more repetitions:-->
                     <gml:metaDataProperty xlink:type="simple" xlink:href="?" xlink:role="?" xlink:arcrole="?" xlink:title="?" xlink:show="?" xlink:actuate="?" gml:remoteSchema="?" about="?">
                        <!--You may enter ANY elements at this point-->
                     </gml:metaDataProperty>
                     <!--Optional:-->
                     <gml:description xlink:type="simple" xlink:href="?" xlink:role="?" xlink:arcrole="?" xlink:title="?" xlink:show="?" xlink:actuate="?" gml:remoteSchema="?">?</gml:description>
                     <!--Zero or more repetitions:-->
                     <gml:name codeSpace="?">?</gml:name>
                  </gml:_Surface>
               </ns:lokatie>
               <!--Optional:-->
               <ns:registratie StUF:noValue="?" StUF:exact="true">?</ns:registratie>
            </ns:anderZaakObject>
```

Denk aan:

```xml
            <ns:anderZaakObject>
               <ns:omschrijving>{{ kaart-veldnaam }}</ns:omschrijving>
               <ns:lokatie>
                            <gml:Point srsName="http://www.opengis.net/def/crs/EPSG/0/4326">
                                <gml:pos>{{ lng }} {{ lat }}</gml:pos>
                            </gml:Point>
               </ns:lokatie>
            </ns:anderZaakObject>
```
