### ISSUE TITLE
Analyse and fix CSP issues based on CSP reports

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#807]
CSP and CSP reports was implemented in #791 

However, it's disabled by default. It should be enabled to analyse all hits and all hits should be solved.

**Tasks**

- [x] Ensure Formio.js machinery still works with unsafe-eval blocked
    - [x] Set up https://github.com/formio/protected-eval
    - [x] Pre-compile custom templates (done via ejs-loader in Webpack)
    - [x] Test all components
        - [x] File uploads
        - [x] Formio WYSIWYG content with inline styles
- [x] Ensure that nonces are added for inline styles
    - [x] Custom logo on form detail page
    - [x] Design tokens in master template
- [x] Fix specific components (https://github.com/open-formulieren/open-forms/issues/807#issuecomment-1019884345)
    - [x] Signature
    - [x] Maps (check)
    - [x] Columns (check)
    - [x] Free text (WYSIWYG & inline styles)
- [x] Add nonces to inline scripts
    - [x] Override `digid_herkenning/post_binding.html` template (5d90e00ce7b1b89115afde28614d92c74e7c91ab)
    - [x] Analytics scripts (bfb8c21b0665994c8efb22fb0816e17db6a7b2ba)
    - [x] Payments page script auto submit(bfb8c21b0665994c8efb22fb0816e17db6a7b2ba)

**Comment by joeribekker** [comment]
Update from Shea on the CSP status.  Most of the issues in the front end are solved but a couple of components aren’t working as they should be.

PR Open Forms: https://github.com/open-formulieren/open-forms/pull/1170
PR Open Forms SDK: https://github.com/open-formulieren/open-forms-sdk/pull/140

**Signature**

Errror: 
```
[Report Only] Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' http://localhost:3000/ 'nonce-WKITyos8BFsoF29PVlbOkA=='". Either the 'unsafe-inline' keyword, a hash ('sha256-7jPXitAmW5luCnpMQQGulV40bQXmdGjm0MJCccHWS8U='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
```
Possibly because it relies on an image?  Uses canvas https://www.w3schools.com/html/html5_canvas.asp as an html element

**Maps**

doesn’t render the map, most likely because it relies on our custom template and custom templates are currently turned off

**Columns**

doesn’t format properly, fields are one on top of another most likely because it relies on our custom template and custom templates are currently turned off

**Free Text (Vrijtekst)**

Just doesn’t render but I could not get the Free text component to render on master either so it may not be CSP related.  However I suspect this will have issues as well since I think it relies on TinyMCE and I don’t think TinyMCE is CSP compliant however this would still need to be looked into
