### ISSUE TITLE
Submission flow improvements and hardening

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#839]
After brainstorm with Sergei, we identified several optimizations, improvements and hardening to make the submission flow better. Notes are written down below as tasks.

**Tasks**

* [x] Register submission -> CeleryOnce. No separate tasks for retry/main behaviour (currently they are).
* [x] Maybe behaviour can be stripped down/removed. Instead if the main flow fails, let retry flow pick it up.
* [x] Set timeout on requests instead of timeouts on tasks. This can be global as far as I'm concerned.
* [x] Change admin action to start retry flow instead of just retry the registration backend.
* [x] Introduce retry chain: Register submission; Update appointment, Update registration with payment
* [x] Remove maybe retry from appointment (prolly similar to point 2)
* [x] Remove code duplication in `emails.py`: The `else`-statement can be replaced with calling `send_confirmation_email_after_payment...`
* [x] Registration retry flow, explicitly does not try to use the obtained zaak number (and override the OF-number). However, it should store the OF-number with the Zaak as "kenmerk".
* [x] Write (extensive) tests for the on_completion_retry workflow
* [x] Ensure task results are "forgotten" in the retry chain
* [x] Make sure if the initial appointment fails, the user is redirected back to the summary screen with an error message.
