### ISSUE TITLE
Show fieldsets (veldengroep) in summary page

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#928]
**Tasks**

* [x] Make sure the fieldset element renders its label in the summary page, preferably in bold to indicate a group.
* [x] Make the solution as generic as possible by checking the Formio component layout/nested (or whatever) attributes, to render the components label.
* [x] Ensure data within columns is also displayed.  Currently anything within a column is not displayed in the summary page.

A form definition like this:

![image](https://user-images.githubusercontent.com/96970/141787971-a570c8fc-01bb-47a5-8699-4617387de008.png)

Should be rendered in the summary page like this:

**Kind 1**
Naam: Jane Doe
Geboortedatum: 01-01-1990

**Kind 2**
Naam: John Doe
Geboortedatum: 01-01-1990

**Comment by sergei-maertens** [comment]
Additional info: it's not even displaying the components inside the fielset - I have two fieldset configured in https://open-forms.test.maykin.opengem.nl/demo-22-november-2021/ and this is the summary:

![image](https://user-images.githubusercontent.com/5518550/142663935-2e97dd70-0bba-453b-8282-b45e9833ba2d.png)

**Comment by sergei-maertens** [comment]
This may very much be related to the `columns` component as well
