### ISSUE TITLE
On the form confirmation page, show navigation buttons to guide the user

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#940]
**Tasks**

* [x] Allow adding links to the confirmation page text via the TinyMCE editor in the "Bevestiging" tab
* [x] Add boolean option in the "Bevestiging" tab to add the link "Terug naar de website" below the download link. This link points to the same page as the redirect target for the main page.
* [x] Make sure the "Bevestiging" menu item (frontend) has a check mark (to indicate it's done).

**Comment by alextreme** [comment]
Deassigning due to shifting Shea to a different project
