### ISSUE TITLE
Add plugin configuration test function

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#941]
This function should validate the configuration for a plugin and preferably test if it actually works and preferably show in the admin what is correctly (or not) configured.

**Tasks**

* [x] Add abstract `Plugin.check_config` function that validates the configuration and connection
* [x] Add abstract `Plugin.get_config_actions` function that returns useful links to configuration and/or test pages (this gives a better UX than the huge config menu)
* [x] Implement these functions for ZGW
* [x] Implement these functions for E-mail
* [x] Implement these functions for Objects (retrieve list of objects, doesn't matter what type)
* [x] Implement these functions for StUF-ZDS (see below)
* [x] Implement these functions for Bestanden (check root access)
* [x] Implement these functions for StUF-BG (see below)
* [x] Implement these functions for KvK (see below)
* [x] Implement these functions for Haal Centraal (see below)
* [x] Implement these functions for Ogone (GET op geconfigueerde URL)
* [x] Implement these functions for JCC (get_available_products)
* [x] Implement these functions for Qmatic (get_available_products)
* [x] Implement these functions for BAG (see below)
* [x] Add config overview admin page to show the results of each plugin

Various optimizations and improvements can be done later, noted down in #956 

@joeribekker stuf-zds request, foutmeldingen van stuf-bg, kvk en haal-centraal

**KvK**

```
GET https://api.kvk.nl/api/v1/zoeken?kvkNummer=68750110
```
Response:
```
{
    "pagina": 1,
    "aantal": 10,
    "totaal": 1,
    "resultaten": [
        {
            "kvkNummer": "68750110",
```

Check of het kvkNummer uit de response overeenkomst met de query param.
Dit werkt voor zowel test als productie omgeving.

**StUF-ZDS**

DIt request naar het endpoint BeantwoordVraag (even netjes met zender/ontvanger/tijdstip/etc variabele zoals bij de andere requests):

SOAP-action header: http://www.egem.nl/StUF/sector/zkn/0310/geefZaakdetails_ZakLv01

```
      <ZKN:zakLv01 xmlns:StUF="http://www.egem.nl/StUF/StUF0301" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:ZKN="http://www.egem.nl/StUF/sector/zkn/0310" xmlns:BG="http://www.egem.nl/StUF/sector/bg/0310" xmlns:gml="http://www.opengis.net/gml">
            <ZKN:stuurgegevens>
                <StUF:berichtcode>Lv01</StUF:berichtcode>
                <StUF:zender>
                    <StUF:organisatie>KING</StUF:organisatie>
                    <StUF:applicatie>KING</StUF:applicatie>
                    <StUF:gebruiker></StUF:gebruiker>
                </StUF:zender>
                <StUF:ontvanger>
                    <StUF:organisatie>KING</StUF:organisatie>
                    <StUF:applicatie>KING</StUF:applicatie>
                    <StUF:gebruiker></StUF:gebruiker>
                </StUF:ontvanger>
                <StUF:tijdstipBericht>2013041109255225</StUF:tijdstipBericht>
                <StUF:entiteittype>ZAK</StUF:entiteittype>
            </ZKN:stuurgegevens>
            <ZKN:parameters>
                <StUF:sortering>0</StUF:sortering>
                <StUF:indicatorVervolgvraag>false</StUF:indicatorVervolgvraag>
            </ZKN:parameters>
            <ZKN:gelijk StUF:entiteittype="ZAK">
                <ZKN:identificatie>5700000000000000000000000000000000000001</ZKN:identificatie>
            </ZKN:gelijk>
            <ZKN:scope>
                <ZKN:object StUF:entiteittype="ZAK">
                    <ZKN:identificatie>5700000000000000000000000000000000000001</ZKN:identificatie>
                    <ZKN:omschrijving>Client</ZKN:omschrijving>
                </ZKN:object>
            </ZKN:scope>
        </ZKN:zakLv01>
```

De verwachte response is:

```
    <?xml version='1.0' encoding='utf-8'?>
    <soap11env:Envelope xmlns:soap11env="http://www.w3.org/2003/05/soap-envelope">
      <soap11env:Body>
        <soap11env:Fault>
          <faultcode>soap11env:client</faultcode>
          <faultstring>Object niet gevonden</faultstring>
          <faultactor/>
          <detail>
...
```

Waarbij het gaat om de `faultString` en verder is het de XML die staat bij `parse_soap_error_text`.

**StUF-BG**

Test met BSN 111222333
Zou dezelfde foutmelding moeten geven als hierboven.

**Haal Centraal**

Test met BSN 111222333
Sucess als er een HTTP 404 terugkomt met daarin:

```
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_NotFound",
    "title": "Opgevraagde resource bestaat niet.",
    "status": 404,
    "detail": "Ingeschreven persoon niet gevonden met burgerservicenummer 111222333.",
    "instance": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/111222333",
    "code": "notFound"
}
```

waarbij je kan controleren op het "status" veld dat 404 moet bevatten (de rest van de gegevens ligt volgens mij niet vast).

**BAG**

```
https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2/adressen?postcode=1000AA&huisnummer=1
```

Dit geeft een HTTP 200.
