### ISSUE TITLE
Demo sprint 9 checklist

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#974]
**High prio**

- [x] Fix e-mail layout
    - [x] logo is scaled too big
    - [x] header bg color should be white (tweak design tokens)
- [x] Check failing submission: https://open-forms.test.maykin.opengem.nl/admin/submissions/submission/346/change/ (@sergei-maertens)
- [x] Investigate unexpected HTTP 403's while filling out the form - happens even when going from step to next step (@shea-maykinmedia)
- [x] SharePoint credentials @joeribekker 
- [x] Verify PDF output (confirmation) @SilviaAmAm 
- [x] update SDK translations (@sergei-maertens)
- [x] Submit/Next button hover-state is grey (should be dark blue, like the cookie hover buttons) (@sergei-maertens)
- [x] Opening payment URL from e-mail is broken (see Sentry) @sergei-maertens 

**Low prio**

- [x] Check that the default mail templates in global config are properly NL-version instead of EN (for new instances) @sergei-maertens 
- [ ] On FormIO form invalid -> logic checking spinner button keeps spinning
- [x] Component multiple values (array value) overview is not properly formatted as list (comma separated?) @SilviaAmAm 
- [ ] Logic: checkbox true conditions not working yet (#810) @SilviaAmAm 
- [ ] fieldsets not in summary: not just the fieldset, but the nested components aren't either! (#928)
- [x] Missing admin frontend translation `Receives confirmation email` @SilviaAmAm 
- [ ] The PDF report generation breaks with a multivalue field if that field is left empty (tested with email field). 

~~TinyMCE hover -> change cursor in "cursor" rather than default cursor (same as hovering a text input)~~ scrapped, iframe mess

**Comment by sergei-maertens** [comment]
Not done

**Comment by sergei-maertens** [comment]
mmm no, not closed.
