### ISSUE TITLE
Move most StUF-ZDS config to form level

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#992]
Rework on StUF-ZDS. Basically, we do no longer have any global StUF-ZDS configuration except for the `Gemeentecode`.

**Tasks**

* [x] Add `Gemeentecode` to registration serializer on form level (it can be overruled on form level) - This will be the only global setting
* [x] Remove `Zaaktype code` and `Zaaktype omschrijving` from the global settings (no more global setting)
* [x] Move `Zaaktype status code`, `Zaaktype status omschrijving`, `Documenttype omschrijving` to for level (no more global setting)
* [x] Make `Zaaktype code`, `Zaaktype status code`, and `Documenttype omschrijving` required on form level
* [x] Rename `Documenttype omschrijving` to `Documenttype omschrijving voor inzending`.
